roomsElevator = [
    # crateria
    {"address": 0x0797B5, "doorCount": 3, "name": "[Elevator to Blue Brinstar]", "direction": "down"},
    {"address": 0x079E9F, "doorCount": 4, "name": "Morph Ball Room", "direction": "up"},
    {"address": 0x07962A, "doorCount": 3, "name": "[Elevator to Red Brinstar]", "direction": "down"},
    {"address": 0x07A322, "doorCount": 7, "name": "Caterpillar Room", "direction": "up"},
    {"address": 0x079938, "doorCount": 3, "name": "[Elevator to Green Brinstar]", "direction": "down"},
    {"address": 0x079AD9, "doorCount": 11, "name": "Green Brinstar Main Shaft [etecoon room]", "direction": "up"},
    {"address": 0x0794CC, "doorCount": 3, "name": "[Elevator to Maridia]", "direction": "down"},
    {"address": 0x07D30B, "doorCount": 4, "name": "Maridia Elevator Room", "direction": "up"},

    # brinstar
    {"address": 0x07A6A1, "doorCount": 4, "name": "Warehouse Entrance", "direction": "down"},
    {"address": 0x07A7DE, "doorCount": 8, "name": "Business Center", "direction": "up"},

    # norfair
    {"address": 0x07AF3F, "doorCount": 4, "name": "[Elevator to Lower Norfair]", "direction": "down"},
    {"address": 0x07B236, "doorCount": 4, "name": "Main Hall", "direction": "up"},
]

roomsDoor = [
    # crateria
    {"address": 0x079969, "doorCount": 2, "name": "Lower Mushrooms", "direction": "left"},
    {"address": 0x0795FF, "doorCount": 2, "name": "The Moat", "direction": "right"},
    {"address": 0x07948C, "doorCount": 3, "name": "Crateria Keyhunter Room", "direction": "down"},
    {"address": 0x079E9F, "doorCount": 4, "name": "Morph Ball Room", "direction": "left"},

    # green/pink brinstar
    {"address": 0x079938, "doorCount": 3, "name": "[Elevator to Green Brinstar]", "direction": "right"},
    {"address": 0x079E52, "doorCount": 3, "name": "Green Hill Zone", "direction": "right"},
    {"address": 0x079FBA, "doorCount": 2, "name": "Noob Bridge", "direction": "right"},

    # wrecked ship
    {"address": 0x0793FE, "doorCount": 6, "name": "West Ocean", "direction": "left"},
    {"address": 0x07957D, "doorCount": 2, "name": "Crab Maze", "direction": "left"},

    # lower norfair
    {"address": 0x07AF14, "doorCount": 2, "name": "Lava Dive Room", "direction": "right"},
    {"address": 0x07B656, "doorCount": 2, "name": "Three Muskateers' Room", "direction": "left"},

    # norfair
    {"address": 0x07A6A1, "doorCount": 4, "name": "Warehouse Entrance", "direction": "left"},
    {"address": 0x07AD5E, "doorCount": 5, "name": "Single Chamber", "direction": "right"},
    {"address": 0x07AE74, "doorCount": 4, "name": "Kronic Boost Room", "direction": "left"},

    # maridia
    {"address": 0x07CFC9, "doorCount": 5, "name": "Main Street", "direction": "down"},
    {"address": 0x07D21C, "doorCount": 4, "name": "Crab Hole", "direction": "left"},
    {"address": 0x0795A8, "doorCount": 2, "name": "[Crab Maze to Elevator]", "direction": "right"},
    {"address": 0x07D104, "doorCount": 2, "name": "Red Fish Room", "direction": "left"},

    # red brinstar
    {"address": 0x07A253, "doorCount": 5, "name": "Red Tower", "direction": "left"},
    {"address": 0x07A322, "doorCount": 7, "name": "Caterpillar Room", "direction": "right"},
    {"address": 0x07962A, "doorCount": 3, "name": "[Elevator to Red Brinstar]", "direction": "all"},
    {"address": 0x07CF80, "doorCount": 3, "name": "East Tunnel", "direction": "right"},
    {"address": 0x07CF80, "doorCount": 3, "name": "East Tunnel", "direction": "right"},
    {"address": 0x07CEFB, "doorCount": 4, "name": "Glass Tunnel", "direction": "up"}
]

rooms = [
{"address": 0x0791F8, "doorCount": 4, "name": "Landing Site"},
{"address": 0x0792B3, "doorCount": 2, "name": "Gauntlet Entrance"},
{"address": 0x0792FD, "doorCount": 7, "name": "Parlor and Alcatraz"},
{"address": 0x0793AA, "doorCount": 1, "name": "Crateria Power Bomb Room"},
{"address": 0x0793D5, "doorCount": 1, "name": "[Parlor Save Room]"},
{"address": 0x0793FE, "doorCount": 6, "name": "West Ocean"},
{"address": 0x079461, "doorCount": 2, "name": "Bowling Alley Path"},
{"address": 0x07948C, "doorCount": 3, "name": "Crateria Keyhunter Room"},
{"address": 0x0794CC, "doorCount": 3, "name": "[Elevator to Maridia]"},
{"address": 0x0794FD, "doorCount": 2, "name": "East Ocean"},
{"address": 0x079552, "doorCount": 2, "name": "Forgotten Highway Kago Room"},
{"address": 0x07957D, "doorCount": 2, "name": "Crab Maze"},
{"address": 0x0795A8, "doorCount": 2, "name": "[Crab Maze to Elevator]"},
{"address": 0x0795D4, "doorCount": 2, "name": "Crateria Tube"},
{"address": 0x0795FF, "doorCount": 2, "name": "The Moat"},
{"address": 0x07962A, "doorCount": 3, "name": "[Elevator to Red Brinstar]"},
{"address": 0x07965B, "doorCount": 2, "name": "Gauntlet Energy Tank Room"},
{"address": 0x07968F, "doorCount": 2, "name": "[West Ocean Geemer Corridor]"},
{"address": 0x0796BA, "doorCount": 5, "name": "Climb"},
{"address": 0x07975C, "doorCount": 2, "name": "Pit Room [Old Mother Brain Room]"},
{"address": 0x0797B5, "doorCount": 3, "name": "[Elevator to Blue Brinstar]"},
{"address": 0x079804, "doorCount": 1, "name": "Bomb Torizo Room"},
{"address": 0x079879, "doorCount": 2, "name": "Flyway"},
{"address": 0x0798E2, "doorCount": 2, "name": "Pre-Map Flyway"},
{"address": 0x07990D, "doorCount": 2, "name": "Terminator Room"},
{"address": 0x079938, "doorCount": 3, "name": "[Elevator to Green Brinstar]"},
{"address": 0x079969, "doorCount": 2, "name": "Lower Mushrooms"},
{"address": 0x079994, "doorCount": 1, "name": "Crateria Map Room"},
{"address": 0x0799BD, "doorCount": 4, "name": "Green Pirates Shaft"},
{"address": 0x0799F9, "doorCount": 2, "name": "Crateria Super Room"},
{"address": 0x079A44, "doorCount": 2, "name": "Final Missile Bombway"},
{"address": 0x079A90, "doorCount": 1, "name": "The Final Missile"},
{"address": 0x07A5ED, "doorCount": 2, "name": "Statues Hallway"},
{"address": 0x07A66A, "doorCount": 3, "name": "Statues Room"},
{"address": 0x079AD9, "doorCount": 11, "name": "Green Brinstar Main Shaft [etecoon room]"},
{"address": 0x079B5B, "doorCount": 2, "name": "Spore Spawn Super Room"},
{"address": 0x079B9D, "doorCount": 2, "name": "Brinstar Pre-Map Room"},
{"address": 0x079BC8, "doorCount": 2, "name": "Early Supers Room"},
{"address": 0x079C07, "doorCount": 1, "name": "Brinstar Reserve Tank Room"},
{"address": 0x079C35, "doorCount": 1, "name": "Brinstar Map Room"},
{"address": 0x079C5E, "doorCount": 2, "name": "Green Brinstar Fireflea Room"},
{"address": 0x079C89, "doorCount": 1, "name": "[Green Brinstar Missile Station]"},
{"address": 0x079CB3, "doorCount": 3, "name": "Dachora Room"},
{"address": 0x079D19, "doorCount": 9, "name": "Big Pink"},
{"address": 0x079D9C, "doorCount": 2, "name": "Spore Spawn Keyhunter Room"},
{"address": 0x079DC7, "doorCount": 2, "name": "Spore Spawn Room"},
{"address": 0x079E11, "doorCount": 2, "name": "Pink Brinstar Power Bomb Room"},
{"address": 0x079E52, "doorCount": 3, "name": "Green Hill Zone"},
{"address": 0x079E9F, "doorCount": 4, "name": "Morph Ball Room"},
{"address": 0x079F11, "doorCount": 3, "name": "Construction Zone"},
{"address": 0x079F64, "doorCount": 2, "name": "Blue Brinstar Energy Tank Room"},
{"address": 0x079FBA, "doorCount": 2, "name": "Noob Bridge"},
{"address": 0x079FE5, "doorCount": 2, "name": "Green Brinstar Beetom Room"},
{"address": 0x07A011, "doorCount": 4, "name": "Etecoon Energy Tank Room"},
{"address": 0x07A051, "doorCount": 1, "name": "Etecoon Super Room"},
{"address": 0x07A07B, "doorCount": 1, "name": "[Dachora Room Energy Charge Station]"},
{"address": 0x07A0A4, "doorCount": 2, "name": "Spore Spawn Farming Room"},
{"address": 0x07A0D2, "doorCount": 2, "name": "Waterway Energy Tank Room"},
{"address": 0x07A107, "doorCount": 1, "name": "First Missile Room"},
{"address": 0x07A130, "doorCount": 2, "name": "Pink Brinstar Hopper Room"},
{"address": 0x07A15B, "doorCount": 1, "name": "Hopper Energy Tank Room"},
{"address": 0x07A184, "doorCount": 1, "name": "[Spore Spawn Save Room]"},
{"address": 0x07A1AD, "doorCount": 2, "name": "Blue Brinstar Boulder Room"},
{"address": 0x07A1D8, "doorCount": 1, "name": "Blue Brinstar Double Missile Room"},
{"address": 0x07A201, "doorCount": 1, "name": "[Green Brinstar Main Shaft Save Room]"},
{"address": 0x07A22A, "doorCount": 1, "name": "[Etecoon Save Room]"},
{"address": 0x07A253, "doorCount": 5, "name": "Red Tower"},
{"address": 0x07A293, "doorCount": 2, "name": "Red Brinstar Fireflea Room"},
{"address": 0x07A2CE, "doorCount": 1, "name": "X-Ray Scope Room"},
{"address": 0x07A2F7, "doorCount": 2, "name": "Hellway"},
{"address": 0x07A322, "doorCount": 7, "name": "Caterpillar Room"},
{"address": 0x07A37C, "doorCount": 1, "name": "Beta Power Bomb Room"},
{"address": 0x07A3AE, "doorCount": 1, "name": "Alpha Power Bomb Room"},
{"address": 0x07A3DD, "doorCount": 2, "name": "Bat Room"},
{"address": 0x07A408, "doorCount": 3, "name": "Below Spazer"},
{"address": 0x07A447, "doorCount": 1, "name": "Spazer Room"},
{"address": 0x07A471, "doorCount": 3, "name": "Warehouse Zeela Room"},
{"address": 0x07A4B1, "doorCount": 1, "name": "Warehouse Energy Tank Room"},
{"address": 0x07A4DA, "doorCount": 3, "name": "Warehouse Keyhunter Room"},
{"address": 0x07A521, "doorCount": 2, "name": "Baby Kraid Room"},
{"address": 0x07A56B, "doorCount": 3, "name": "Kraid Eye Door Room"},
{"address": 0x07A59F, "doorCount": 2, "name": "Kraid Room"},
{"address": 0x07A618, "doorCount": 1, "name": "[Red Tower Energy Charge Station]"},
{"address": 0x07A641, "doorCount": 1, "name": "[Kraid Recharge Station]"},
{"address": 0x07A6A1, "doorCount": 4, "name": "Warehouse Entrance"},
{"address": 0x07A6E2, "doorCount": 1, "name": "Varia Suit Room"},
{"address": 0x07A70B, "doorCount": 1, "name": "[Kraid Save Room]"},
{"address": 0x07A734, "doorCount": 1, "name": "[Caterpillar Save Room]"},
{"address": 0x07A75D, "doorCount": 2, "name": "Ice Beam Acid Room"},
{"address": 0x07A788, "doorCount": 2, "name": "Cathedral"},
{"address": 0x07A7B3, "doorCount": 2, "name": "Cathedral Entrance"},
{"address": 0x07A7DE, "doorCount": 8, "name": "Business Center"},
{"address": 0x07A815, "doorCount": 4, "name": "Ice Beam Gate Room"},
{"address": 0x07A865, "doorCount": 2, "name": "Ice Beam Tutorial Room"},
{"address": 0x07A890, "doorCount": 1, "name": "Ice Beam Room"},
{"address": 0x07A8B9, "doorCount": 3, "name": "Ice Beam Snake Room"},
{"address": 0x07A8F8, "doorCount": 2, "name": "Crumble Shaft"},
{"address": 0x07A923, "doorCount": 5, "name": "Crocomire Speedway"},
{"address": 0x07A98D, "doorCount": 2, "name": "Crocomire's Room"},
{"address": 0x07A9E5, "doorCount": 1, "name": "Hi Jump Boots Room"},
{"address": 0x07AA0E, "doorCount": 2, "name": "Crocomire Escape"},
{"address": 0x07AA41, "doorCount": 2, "name": "Hi Jump Energy Tank Room"},
{"address": 0x07AA82, "doorCount": 4, "name": "Post Crocomire Farming Room"},
{"address": 0x07AAB5, "doorCount": 1, "name": "[Post Crocomire Save Room]"},
{"address": 0x07AADE, "doorCount": 1, "name": "Post Crocomire Power Bomb Room"},
{"address": 0x07AB07, "doorCount": 4, "name": "Post Crocomire Shaft"},
{"address": 0x07AB3B, "doorCount": 1, "name": "Post Crocomire Missile Room"},
{"address": 0x07AB64, "doorCount": 2, "name": "Grapple Tutorial Room 3"},
{"address": 0x07AB8F, "doorCount": 2, "name": "Post Crocomire Jump Room"},
{"address": 0x07ABD2, "doorCount": 2, "name": "Grapple Tutorial Room 2"},
{"address": 0x07AC00, "doorCount": 2, "name": "Grapple Tutorial Room 1"},
{"address": 0x07AC2B, "doorCount": 2, "name": "Grapple Beam Room"},
{"address": 0x07AC5A, "doorCount": 1, "name": "Norfair Reserve Tank Room"},
{"address": 0x07AC83, "doorCount": 2, "name": "Green Bubbles Missile Room"},
{"address": 0x07ACB3, "doorCount": 7, "name": "Bubble Mountain"},
{"address": 0x07ACF0, "doorCount": 2, "name": "Speed Booster Hall"},
{"address": 0x07AD1B, "doorCount": 1, "name": "Speed Booster Room"},
{"address": 0x07AD5E, "doorCount": 5, "name": "Single Chamber"},
{"address": 0x07ADAD, "doorCount": 3, "name": "Double Chamber"},
{"address": 0x07ADDE, "doorCount": 1, "name": "Wave Beam Room"},
{"address": 0x07AE07, "doorCount": 2, "name": "Spiky Platforms Tunnel"},
{"address": 0x07AE32, "doorCount": 2, "name": "Volcano Room"},
{"address": 0x07AE74, "doorCount": 4, "name": "Kronic Boost Room"},
{"address": 0x07AEB4, "doorCount": 2, "name": "Magdollite Tunnel"},
{"address": 0x07AEDF, "doorCount": 3, "name": "Purple Shaft"},
{"address": 0x07AF14, "doorCount": 2, "name": "Lava Dive Room"},
{"address": 0x07AF3F, "doorCount": 4, "name": "[Elevator to Lower Norfair]"},
{"address": 0x07AF72, "doorCount": 3, "name": "Upper Norfair Farming Room"},
{"address": 0x07AFA3, "doorCount": 2, "name": "Rising Tide"},
{"address": 0x07AFCE, "doorCount": 3, "name": "Acid Snakes Tunnel"},
{"address": 0x07AFFB, "doorCount": 2, "name": "Spiky Acid Snakes Tunnel"},
{"address": 0x07B026, "doorCount": 2, "name": "[Crocomire Recharge Room]"},
{"address": 0x07B051, "doorCount": 1, "name": "Purple Farming Room"},
{"address": 0x07B07A, "doorCount": 2, "name": "Bat Cave"},
{"address": 0x07B0B4, "doorCount": 1, "name": "Norfair Map Room"},
{"address": 0x07B0DD, "doorCount": 1, "name": "[Bubble Mountain Save Room]"},
{"address": 0x07B106, "doorCount": 2, "name": "Frog Speedway"},
{"address": 0x07B139, "doorCount": 2, "name": "Red Pirate Shaft"},
{"address": 0x07B167, "doorCount": 2, "name": "[Business Center Save Room]"},
{"address": 0x07B192, "doorCount": 1, "name": "[Crocomire Save Room]"},
{"address": 0x07B1BB, "doorCount": 1, "name": "[Elevator Save Room]"},
{"address": 0x07B1E5, "doorCount": 2, "name": "Acid Statue Room"},
{"address": 0x07B236, "doorCount": 4, "name": "Main Hall"},
{"address": 0x07B283, "doorCount": 2, "name": "Golden Torizo's Room"},
{"address": 0x07B2DA, "doorCount": 2, "name": "Fast Ripper Room"},
{"address": 0x07B305, "doorCount": 1, "name": "[Screw Attack Energy Charge Room]"},
{"address": 0x07B32E, "doorCount": 2, "name": "Ridley's Room"},
{"address": 0x07B37A, "doorCount": 2, "name": "Lower Norfair Farming Room"},
{"address": 0x07B3A5, "doorCount": 5, "name": "Fast Pillars Setup Room"},
{"address": 0x07B3E1, "doorCount": 1, "name": "[[unused room]]"},
{"address": 0x07B40A, "doorCount": 2, "name": "Mickey Mouse Room"},
{"address": 0x07B457, "doorCount": 2, "name": "Pillar Room"},
{"address": 0x07B482, "doorCount": 2, "name": "Plowerhouse Room"},
{"address": 0x07B4AD, "doorCount": 3, "name": "The Worst Room In The Game"},
{"address": 0x07B4E5, "doorCount": 2, "name": "Amphitheatre"},
{"address": 0x07B510, "doorCount": 3, "name": "Lower Norfair Spring Ball Maze Room"},
{"address": 0x07B55A, "doorCount": 2, "name": "Lower Norfair Escape Power Bomb Room"},
{"address": 0x07B585, "doorCount": 4, "name": "Red Keyhunter Shaft"},
{"address": 0x07B5D5, "doorCount": 2, "name": "Wasteland"},
{"address": 0x07B62B, "doorCount": 2, "name": "Metal Pirates Room"},
{"address": 0x07B656, "doorCount": 2, "name": "Three Muskateers' Room"},
{"address": 0x07B698, "doorCount": 1, "name": "Ridley Tank Room"},
{"address": 0x07B6C1, "doorCount": 3, "name": "Screw Attack Room"},
{"address": 0x07B6EE, "doorCount": 3, "name": "Lower Norfair Fireflea Room"},
{"address": 0x07B741, "doorCount": 1, "name": "[Red Keyhunter Shaft Save Room]"},
{"address": 0x07C98E, "doorCount": 3, "name": "Bowling Alley"},
{"address": 0x07CA08, "doorCount": 2, "name": "Wrecked Ship Entrance"},
{"address": 0x07CA52, "doorCount": 3, "name": "Attic"},
{"address": 0x07CAAE, "doorCount": 1, "name": "Wrecked Ship East Missile Room"},
{"address": 0x07CAF6, "doorCount": 7, "name": "Wrecked Ship Main Shaft"},
{"address": 0x07CB8B, "doorCount": 2, "name": "Spiky Death Room"},
{"address": 0x07CBD5, "doorCount": 3, "name": "Electric Death Room"},
{"address": 0x07CC27, "doorCount": 1, "name": "Wrecked Ship Energy Tank Room"},
{"address": 0x07CC6F, "doorCount": 3, "name": "Basement"},
{"address": 0x07CCCB, "doorCount": 1, "name": "Wrecked Ship Map Room"},
{"address": 0x07CD13, "doorCount": 1, "name": "Phantoon's Room"},
{"address": 0x07CD5C, "doorCount": 2, "name": "Sponge Bath"},
{"address": 0x07CDA8, "doorCount": 1, "name": "Wrecked Ship West Super Room"},
{"address": 0x07CDF1, "doorCount": 1, "name": "Wrecked Ship East Super Room"},
{"address": 0x07CE40, "doorCount": 2, "name": "Gravity Suit Room"},
{"address": 0x07CE8A, "doorCount": 1, "name": "[Wrecked Ship Save Room]"},
{"address": 0x07CED2, "doorCount": 1, "name": "[Glass Tunnel Save Room]"},
{"address": 0x07CEFB, "doorCount": 4, "name": "Glass Tunnel"},
{"address": 0x07CF54, "doorCount": 2, "name": "West Tunnel"},
{"address": 0x07CF80, "doorCount": 3, "name": "East Tunnel"},
{"address": 0x07CFC9, "doorCount": 5, "name": "Main Street"},
{"address": 0x07D017, "doorCount": 4, "name": "Fish Tank"},
{"address": 0x07D055, "doorCount": 1, "name": "Mama Turtle Room"},
{"address": 0x07D08A, "doorCount": 2, "name": "Crab Tunnel"},
{"address": 0x07D0B9, "doorCount": 6, "name": "Mt. Everest"},
{"address": 0x07D104, "doorCount": 2, "name": "Red Fish Room"},
{"address": 0x07D13B, "doorCount": 1, "name": "Watering Hole"},
{"address": 0x07D16D, "doorCount": 2, "name": "Northwest Maridia Bug Room"},
{"address": 0x07D1A3, "doorCount": 3, "name": "Crab Shaft"},
{"address": 0x07D1DD, "doorCount": 3, "name": "Pseudo Plasma Spark Room"},
{"address": 0x07D21C, "doorCount": 4, "name": "Crab Hole"},
{"address": 0x07D252, "doorCount": 2, "name": "[Tunnel to West Sand Hall]"},
{"address": 0x07D27E, "doorCount": 2, "name": "Plasma Tutorial Room"},
{"address": 0x07D2AA, "doorCount": 1, "name": "Plasma Room"},
{"address": 0x07D2D9, "doorCount": 2, "name": "Thread The Needle Room"},
{"address": 0x07D30B, "doorCount": 4, "name": "Maridia Elevator Room"},
{"address": 0x07D340, "doorCount": 4, "name": "Plasma Spark Room"},
{"address": 0x07D387, "doorCount": 2, "name": "Plasma Climb"},
{"address": 0x07D3B6, "doorCount": 1, "name": "Maridia Map Room"},
{"address": 0x07D3DF, "doorCount": 1, "name": "[Maridia Elevator Save Room]"},
{"address": 0x07D408, "doorCount": 2, "name": "[Vertical Tube]"},
{"address": 0x07D433, "doorCount": 3, "name": "Bug Sand Hole"},
{"address": 0x07D461, "doorCount": 3, "name": "West Sand Hall"},
{"address": 0x07D48E, "doorCount": 3, "name": "Oasis"},
{"address": 0x07D4C2, "doorCount": 3, "name": "East Sand Hall"},
{"address": 0x07D4EF, "doorCount": 2, "name": "West Sand Hole"},
{"address": 0x07D51E, "doorCount": 2, "name": "East Sand Hole"},
{"address": 0x07D54D, "doorCount": 2, "name": "[West Sand Fall]"},
{"address": 0x07D57A, "doorCount": 2, "name": "[East Sand Fall]"},
{"address": 0x07D5A7, "doorCount": 6, "name": "Aqueduct"},
{"address": 0x07D5EC, "doorCount": 2, "name": "Butterfly Room"},
{"address": 0x07D617, "doorCount": 2, "name": "Botwoon Hallway"},
{"address": 0x07D646, "doorCount": 4, "name": "Pants Room"},
{"address": 0x07D69A, "doorCount": 2, "name": "[Pants Room West half]"},
{"address": 0x07D6D0, "doorCount": 1, "name": "Spring Ball Room"},
{"address": 0x07D6FD, "doorCount": 1, "name": "Below Botwoon Energy Tank"},
{"address": 0x07D72A, "doorCount": 3, "name": "Colosseum"},
{"address": 0x07D765, "doorCount": 1, "name": "[Aqueduct Save Room]"},
{"address": 0x07D78F, "doorCount": 2, "name": "The Precious Room"},
{"address": 0x07D7E4, "doorCount": 4, "name": "Botwoon Energy Tank Room"},
{"address": 0x07D81A, "doorCount": 2, "name": "[Colosseum Save Room]"},
{"address": 0x07D845, "doorCount": 1, "name": "[Halfie Climb Missile Station]"},
{"address": 0x07D86E, "doorCount": 1, "name": "[Bug Sand Fall]"},
{"address": 0x07D898, "doorCount": 2, "name": "[Botwoon Sand Fall]"},
{"address": 0x07D8C5, "doorCount": 2, "name": "Shaktool Room"},
{"address": 0x07D913, "doorCount": 4, "name": "Halfie Climb Room"},
{"address": 0x07D95E, "doorCount": 2, "name": "Botwoon's Room"},
{"address": 0x07D9AA, "doorCount": 1, "name": "Space Jump Room"},
{"address": 0x07D9D4, "doorCount": 1, "name": "[Colosseum Energy Charge Room]"},
{"address": 0x07D9FE, "doorCount": 2, "name": "Cactus Alley [West]"},
{"address": 0x07DA2B, "doorCount": 2, "name": "Cactus Alley [East]"},
{"address": 0x07DA60, "doorCount": 2, "name": "Draygon's Room"},
{"address": 0x07DAAE, "doorCount": 4, "name": "Tourian First Room"},
{"address": 0x07DAE1, "doorCount": 2, "name": "Metroid Room 1"},
{"address": 0x07DB31, "doorCount": 2, "name": "Metroid Room 2"},
{"address": 0x07DB7D, "doorCount": 2, "name": "Metroid Room 3"},
{"address": 0x07DBCD, "doorCount": 2, "name": "Metroid Room 4"},
{"address": 0x07DC19, "doorCount": 2, "name": "Blue Hopper Room"},
{"address": 0x07DC65, "doorCount": 2, "name": "Dust Torizo Room"},
{"address": 0x07DCB1, "doorCount": 2, "name": "Big Boy Room"},
{"address": 0x07DCFF, "doorCount": 3, "name": "Seaweed Room"},
{"address": 0x07DD2E, "doorCount": 1, "name": "Tourian Recharge Room"},
{"address": 0x07DD58, "doorCount": 2, "name": "Mother Brain Room"},
{"address": 0x07DDC4, "doorCount": 2, "name": "Tourian Eye Door Room"},
{"address": 0x07DDF3, "doorCount": 3, "name": "Rinka Shaft"},
{"address": 0x07DE23, "doorCount": 1, "name": "[Mother Brain Save Room]"},
{"address": 0x07DE4D, "doorCount": 2, "name": "Tourian Escape Room 1"},
{"address": 0x07DE7A, "doorCount": 2, "name": "Tourian Escape Room 2"},
{"address": 0x07DEA7, "doorCount": 2, "name": "Tourian Escape Room 3"},
{"address": 0x07DEDE, "doorCount": 2, "name": "Tourian Escape Room 4"},
{"address": 0x07DF1B, "doorCount": 1, "name": "[Tourian First Save Room]"},
{"address": 0x07DF45, "doorCount": 1, "name": "[Ceres Elevator Room]"},
{"address": 0x07DF8D, "doorCount": 2, "name": "[Ceres Jump Tutorial Room]"},
{"address": 0x07DFD7, "doorCount": 2, "name": "[Ceres Staircase Room]"},
{"address": 0x07E021, "doorCount": 2, "name": "[Ceres Dead Scientists Room]"},
{"address": 0x07E06B, "doorCount": 2, "name": "[Ceres Last Corridor]"},
{"address": 0x07E0B5, "doorCount": 1, "name": "[Ceres Ridley Room]"},
{"address": 0x07E82C, "doorCount": 4, "name": "[Tile Debug Room]"}
]
