
from rando.Items import ItemManager
from rando.ItemLocContainer import ItemLocation
from logic.logic import Logic

_locs = Logic.locationsDict()
vanillaItemLocations = [
    ItemLocation(ItemManager.getItem('Morph'), _locs['Morphing Ball']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (blue Brinstar bottom)']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (blue Brinstar middle)']),
    ItemLocation(ItemManager.getItem('ETank'), _locs['Energy Tank, Brinstar Ceiling']),
    ItemLocation(ItemManager.getItem('Bomb'), _locs['Bomb']),
    ItemLocation(ItemManager.getItem('ETank'), _locs['Energy Tank, Terminator']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (Crateria bottom)']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (Crateria middle)']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (green Brinstar below super missile)']),
    ItemLocation(ItemManager.getItem('Reserve'), _locs['Reserve Tank, Brinstar']),
    ItemLocation(ItemManager.getItem('Super'), _locs['Super Missile (green Brinstar top)']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (green Brinstar behind missile)']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (green Brinstar behind reserve tank)']),
    ItemLocation(ItemManager.getItem('SporeSpawn'), _locs['Spore Spawn']),
    ItemLocation(ItemManager.getItem('Charge'), _locs['Charge Beam']),
    ItemLocation(ItemManager.getItem('Super'), _locs['Super Missile (pink Brinstar)']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (pink Brinstar top)']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (pink Brinstar bottom)']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (green Brinstar pipe)']),
    ItemLocation(ItemManager.getItem('Spazer'), _locs['Spazer']),
    ItemLocation(ItemManager.getItem('HiJump'), _locs['Hi-Jump Boots']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (Hi-Jump Boots)']),
    ItemLocation(ItemManager.getItem('ETank'), _locs['Energy Tank (Hi-Jump Boots)']),
    ItemLocation(ItemManager.getItem('Kraid'), _locs['Kraid']),
    ItemLocation(ItemManager.getItem('Varia'), _locs['Varia Suit']),
    ItemLocation(ItemManager.getItem('ETank'), _locs['Energy Tank, Kraid']),
    ItemLocation(ItemManager.getItem('Ice'), _locs['Ice Beam']),
    ItemLocation(ItemManager.getItem('Reserve'), _locs['Reserve Tank, Norfair']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (Norfair Reserve Tank)']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (bubble Norfair green door)']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (bubble Norfair)']),
    ItemLocation(ItemManager.getItem('SpeedBooster'), _locs['Speed Booster']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (Speed Booster)']),
    ItemLocation(ItemManager.getItem('Wave'), _locs['Wave Beam']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (Wave Beam)']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (lava room)']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (above Crocomire)']),
    ItemLocation(ItemManager.getItem('Crocomire'), _locs['Crocomire']),
    ItemLocation(ItemManager.getItem('ETank'), _locs['Energy Tank, Crocomire']),
    ItemLocation(ItemManager.getItem('Grapple'), _locs['Grapple Beam']),
    ItemLocation(ItemManager.getItem('PowerBomb'), _locs['Power Bomb (Crocomire)']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (below Crocomire)']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (Grapple Beam)']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (below Ice Beam)']),
    ItemLocation(ItemManager.getItem('XRayScope'), _locs['X-Ray Scope']),
    ItemLocation(ItemManager.getItem('PowerBomb'), _locs['Power Bomb (red Brinstar sidehopper room)']),
    ItemLocation(ItemManager.getItem('PowerBomb'), _locs['Power Bomb (red Brinstar spike room)']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (red Brinstar spike room)']),
    ItemLocation(ItemManager.getItem('PowerBomb'), _locs['Power Bomb (Crateria surface)']),
    ItemLocation(ItemManager.getItem('Super'), _locs['Super Missile (Crateria)']),
    ItemLocation(ItemManager.getItem('ETank'), _locs['Energy Tank, Gauntlet']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (Crateria gauntlet right)']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (Crateria gauntlet left)']),
    ItemLocation(ItemManager.getItem('PowerBomb'), _locs['Power Bomb (blue Brinstar)']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (blue Brinstar top)']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (blue Brinstar behind missile)']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (Crateria moat)']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (outside Wrecked Ship bottom)']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (Wrecked Ship middle)']),
    ItemLocation(ItemManager.getItem('Phantoon'), _locs['Phantoon']),
    ItemLocation(ItemManager.getItem('Super'), _locs['Right Super, Wrecked Ship']),
    ItemLocation(ItemManager.getItem('Super'), _locs['Super Missile (Wrecked Ship left)']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (outside Wrecked Ship top)']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (outside Wrecked Ship middle)']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (Wrecked Ship top)']),
    ItemLocation(ItemManager.getItem('Reserve'), _locs['Reserve Tank, Wrecked Ship']),
    ItemLocation(ItemManager.getItem('Gravity'), _locs['Gravity Suit']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (Gravity Suit)']),
    ItemLocation(ItemManager.getItem('ETank'), _locs['Energy Tank, Wrecked Ship']),
    ItemLocation(ItemManager.getItem('SpringBall'), _locs['Spring Ball']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (green Maridia shinespark)']),
    ItemLocation(ItemManager.getItem('Super'), _locs['Super Missile (green Maridia)']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (green Maridia tatori)']),
    ItemLocation(ItemManager.getItem('ETank'), _locs['Energy Tank, Mama turtle']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (yellow Maridia false wall)']),
    ItemLocation(ItemManager.getItem('Super'), _locs['Super Missile (yellow Maridia)']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (yellow Maridia super missile)']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (pink Maridia)']),
    ItemLocation(ItemManager.getItem('Super'), _locs['Super Missile (pink Maridia)']),
    ItemLocation(ItemManager.getItem('Botwoon'), _locs['Botwoon']),
    ItemLocation(ItemManager.getItem('ETank'), _locs['Energy Tank, Botwoon']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (Draygon)']),
    ItemLocation(ItemManager.getItem('Reserve'), _locs['Reserve Tank, Maridia']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (left Maridia sand pit room)']),
    ItemLocation(ItemManager.getItem('ETank'), _locs['Energy Tank, Waterway']),
    ItemLocation(ItemManager.getItem('ETank'), _locs['Energy Tank, Brinstar Gate']),
    ItemLocation(ItemManager.getItem('PowerBomb'), _locs['Power Bomb (pink Brinstar)']),
    ItemLocation(ItemManager.getItem('ETank'), _locs['Energy Tank, Etecoons']),
    ItemLocation(ItemManager.getItem('PowerBomb'), _locs['Power Bomb (green Brinstar bottom)']),
    ItemLocation(ItemManager.getItem('Super'), _locs['Super Missile (green Brinstar bottom)']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (Kraid)']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (right Maridia sand pit room)']),
    ItemLocation(ItemManager.getItem('PowerBomb'), _locs['Power Bomb (right Maridia sand pit room)']),
    ItemLocation(ItemManager.getItem('GoldenTorizo'), _locs['Golden Torizo']),
    ItemLocation(ItemManager.getItem('Super'), _locs['Super Missile (Gold Torizo)']),
    ItemLocation(ItemManager.getItem('ScrewAttack'), _locs['Screw Attack']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (Mickey Mouse room)']),
    ItemLocation(ItemManager.getItem('ETank'), _locs['Energy Tank, Firefleas']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (lower Norfair above fire flea room)']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (lower Norfair near Wave Beam)']),
    ItemLocation(ItemManager.getItem('PowerBomb'), _locs['Power Bomb (lower Norfair above fire flea room)']),
    ItemLocation(ItemManager.getItem('PowerBomb'), _locs['Power Bomb (Power Bombs of shame)']),
    ItemLocation(ItemManager.getItem('Ridley'), _locs['Ridley']),
    ItemLocation(ItemManager.getItem('ETank'), _locs['Energy Tank, Ridley']),
    ItemLocation(ItemManager.getItem('Draygon'), _locs['Draygon']),
    ItemLocation(ItemManager.getItem('SpaceJump'), _locs['Space Jump']),
    ItemLocation(ItemManager.getItem('Plasma'), _locs['Plasma Beam']),
    ItemLocation(ItemManager.getItem('Missile'), _locs['Missile (Gold Torizo)']),
    ItemLocation(ItemManager.getItem('MotherBrain'), _locs['Mother Brain']),
]
