var locations = {};

var doors = {};

var aps = {};

locations['vanilla'] = {
    "PowerBombCrateriasurface": {"left": 27, "top": 1, "room": "93aa", "variaArea": "Crateria"},
    "MissileoutsideWreckedShipbottom": {"left": 0, "top": 5, "room": "93fe", "variaArea": "WreckedShip"},
    "MissileoutsideWreckedShiptop": {"left": 1, "top": 0, "room": "93fe", "variaArea": "WreckedShip"},
    "MissileoutsideWreckedShipmiddle": {"left": 0, "top": 2, "room": "93fe", "variaArea": "WreckedShip"},
    "MissileCrateriamoat": {"left": 30, "top": 4, "room": "95ff", "variaArea": "Crateria"},
    "EnergyTankGauntlet": {"left": 11, "top": 2, "room": "965b", "variaArea": "Crateria"},
    "MissileCrateriabottom": {"left": 14, "top": 18, "room": "975c", "variaArea": "Crateria"},
    "Bomb": {"left": 19, "top": 6, "room": "9804", "variaArea": "Crateria"},
    "EnergyTankTerminator": {"left": 6, "top": 6, "room": "990d", "variaArea": "Crateria"},
    "MissileCrateriagauntletright": {"left": 5, "top": 3, "room": "99bd", "variaArea": "Crateria"},
    "MissileCrateriagauntletleft": {"left": 5, "top": 3, "room": "99bd", "variaArea": "Crateria"},
    "SuperMissileCrateria": {"left": 18, "top": 9, "room": "99f9", "variaArea": "Crateria"},
    "MissileCrateriamiddle": {"left": 10, "top": 7, "room": "9a90", "variaArea": "Crateria"},
    "PowerBombgreenBrinstarbottom": {"left": 7, "top": 9, "room": "9ad9", "variaArea": "GreenBrinstar"},
    "SuperMissilepinkBrinstar": {"left": 19, "top": 11, "room": "9b5b", "variaArea": "GreenBrinstar"},
    "MissilegreenBrinstarbelowsupermissile": {"left": 6, "top": 6, "room": "9bc8", "variaArea": "GreenBrinstar"},
    "SuperMissilegreenBrinstartop": {"left": 5, "top": 5, "room": "9bc8", "variaArea": "GreenBrinstar"},
    "ReserveTankBrinstar": {"left": 8, "top": 6, "room": "9c07", "variaArea": "GreenBrinstar"},
    "MissilegreenBrinstarbehindmissile": {"left": 9, "top": 6, "room": "9c07", "variaArea": "GreenBrinstar"},
    "MissilegreenBrinstarbehindreservetank": {"left": 9, "top": 6, "room": "9c07", "variaArea": "GreenBrinstar"},
    "MissilepinkBrinstartop": {"left": 12, "top": 9, "room": "9d19", "variaArea": "GreenBrinstar"},
    "MissilepinkBrinstarbottom": {"left": 12, "top": 12, "room": "9d19", "variaArea": "GreenBrinstar"},
    "ChargeBeam": {"left": 12, "top": 13, "room": "9d19", "variaArea": "GreenBrinstar"},
    "PowerBombpinkBrinstar": {"left": 10, "top": 10, "room": "9e11", "variaArea": "GreenBrinstar"},
    "MissilegreenBrinstarpipe": {"left": 17, "top": 13, "room": "9e52", "variaArea": "GreenBrinstar"},
    "MorphingBall": {"left": 15, "top": 29, "room": "9e9f", "variaArea": "Crateria"},
    "PowerBombblueBrinstar": {"left": 13, "top": 29, "room": "9e9f", "variaArea": "Crateria"},
    "MissileblueBrinstarmiddle": {"left": 22, "top": 29, "room": "9f64", "variaArea": "Crateria"},
    "EnergyTankBrinstarCeiling": {"left": 21, "top": 29, "room": "9f64", "variaArea": "Crateria"},
    "EnergyTankEtecoons": {"left": 1, "top": 12, "room": "a011", "variaArea": "GreenBrinstar"},
    "SuperMissilegreenBrinstarbottom": {"left": 0, "top": 12, "room": "a051", "variaArea": "GreenBrinstar"},
    "EnergyTankWaterway": {"left": 3, "top": 15, "room": "a0d2", "variaArea": "GreenBrinstar"},
    "MissileblueBrinstarbottom": {"left": 18, "top": 30, "room": "a107", "variaArea": "Crateria"},
    "EnergyTankBrinstarGate": {"left": 16, "top": 10, "room": "a15b", "variaArea": "GreenBrinstar"},
    "MissileblueBrinstartop": {"left": 19, "top": 27, "room": "a1d8", "variaArea": "Crateria"},
    "MissileblueBrinstarbehindmissile": {"left": 19, "top": 27, "room": "a1d8", "variaArea": "Crateria"},
    "XRayScope": {"left": 0, "top": 13, "room": "a2ce", "variaArea": "RedBrinstar"},
    "PowerBombredBrinstarsidehopperroom": {"left": 12, "top": 6, "room": "a37c", "variaArea": "RedBrinstar"},
    "PowerBombredBrinstarspikeroom": {"left": 12, "top": 9, "room": "a3ae", "variaArea": "RedBrinstar"},
    "MissileredBrinstarspikeroom": {"left": 11, "top": 9, "room": "a3ae", "variaArea": "RedBrinstar"},
    "Spazer": {"left": 15, "top": 15, "room": "a447", "variaArea": "RedBrinstar"},
    "EnergyTankKraid": {"left": 0, "top": 1, "room": "a4b1", "variaArea": "KraidLair"},
    "MissileKraid": {"left": 4, "top": 0, "room": "a4da", "variaArea": "KraidLair"},
    "VariaSuit": {"left": 2, "top": 1, "room": "a6e2", "variaArea": "Kraid"},
    "Missilelavaroom": {"left": 14, "top": 6, "room": "a788", "variaArea": "UpperNorfair"},
    "IceBeam": {"left": 3, "top": 4, "room": "a890", "variaArea": "UpperNorfair"},
    "MissilebelowIceBeam": {"left": 0, "top": 6, "room": "a8f8", "variaArea": "UpperNorfair"},
    "EnergyTankCrocomire": {"left": 16, "top": 0, "room": "a98d", "variaArea": "Crocomire"},
    "HiJumpBoots": {"left": 5, "top": 8, "room": "a9e5", "variaArea": "UpperNorfair"},
    "MissileaboveCrocomire": {"left": 9, "top": 8, "room": "aa0e", "variaArea": "UpperNorfair"},
    "MissileHiJumpBoots": {"left": 6, "top": 7, "room": "aa41", "variaArea": "UpperNorfair"},
    "EnergyTankHiJumpBoots": {"left": 7, "top": 7, "room": "aa41", "variaArea": "UpperNorfair"},
    "PowerBombCrocomire": {"left": 6, "top": 0, "room": "aade", "variaArea": "Crocomire"},
    "MissilebelowCrocomire": {"left": 11, "top": 5, "room": "ab3b", "variaArea": "Crocomire"},
    "MissileGrappleBeam": {"left": 5, "top": 5, "room": "ab8f", "variaArea": "Crocomire"},
    "GrappleBeam": {"left": 0, "top": 6, "room": "ac2b", "variaArea": "Crocomire"},
    "ReserveTankNorfair": {"left": 16, "top": 4, "room": "ac5a", "variaArea": "UpperNorfair"},
    "MissileNorfairReserveTank": {"left": 16, "top": 4, "room": "ac5a", "variaArea": "UpperNorfair"},
    "MissilebubbleNorfairgreendoor": {"left": 19, "top": 4, "room": "ac83", "variaArea": "UpperNorfair"},
    "MissilebubbleNorfair": {"left": 21, "top": 7, "room": "acb3", "variaArea": "UpperNorfair"},
    "MissileSpeedBooster": {"left": 34, "top": 4, "room": "acf0", "variaArea": "UpperNorfair"},
    "SpeedBooster": {"left": 35, "top": 4, "room": "ad1b", "variaArea": "UpperNorfair"},
    "MissileWaveBeam": {"left": 24, "top": 6, "room": "adad", "variaArea": "UpperNorfair"},
    "WaveBeam": {"left": 27, "top": 6, "room": "adde", "variaArea": "UpperNorfair"},
    "MissileGoldTorizo": {"left": 3, "top": 12, "room": "b283", "variaArea": "LowerNorfair"},
    "SuperMissileGoldTorizo": {"left": 4, "top": 12, "room": "b283", "variaArea": "LowerNorfair"},
    "MissileMickeyMouseroom": {"left": 13, "top": 7, "room": "b40a", "variaArea": "LowerNorfair"},
    "MissilelowerNorfairabovefireflearoom": {"left": 20, "top": 2, "room": "b510", "variaArea": "LowerNorfair"},
    "PowerBomblowerNorfairabovefireflearoom": {"left": 22, "top": 3, "room": "b55a", "variaArea": "LowerNorfair"},
    "PowerBombPowerBombsofshame": {"left": 17, "top": 11, "room": "b5d5", "variaArea": "LowerNorfair"},
    "MissilelowerNorfairnearWaveBeam": {"left": 14, "top": 2, "room": "b656", "variaArea": "LowerNorfair"},
    "EnergyTankRidley": {"left": 0, "top": 1, "room": "b698", "variaArea": "Ridley"},
    "ScrewAttack": {"left": 5, "top": 13, "room": "b6c1", "variaArea": "LowerNorfair"},
    "EnergyTankFirefleas": {"left": 22, "top": 8, "room": "b6ee", "variaArea": "LowerNorfair"},
    "ReserveTankWreckedShip": {"left": 11, "top": 1, "room": "c98e", "variaArea": "WreckedShip"},
    "MissileGravitySuit": {"left": 9, "top": 3, "room": "c98e", "variaArea": "WreckedShip"},
    "MissileWreckedShiptop": {"left": 17, "top": 0, "room": "caae", "variaArea": "WreckedShip"},
    "MissileWreckedShipmiddle": {"left": 8, "top": 6, "room": "caf6", "variaArea": "WreckedShip"},
    "EnergyTankWreckedShip": {"left": 14, "top": 3, "room": "cc27", "variaArea": "WreckedShip"},
    "SuperMissileWreckedShipleft": {"left": 11, "top": 7, "room": "cda8", "variaArea": "WreckedShip"},
    "RightSuperWreckedShip": {"left": 17, "top": 7, "room": "cdf1", "variaArea": "WreckedShip"},
    "GravitySuit": {"left": 6, "top": 3, "room": "ce40", "variaArea": "WreckedShip"},
    "MissilegreenMaridiashinespark": {"left": 0, "top": 8, "room": "cfc9", "variaArea": "WestMaridia"},
    "SuperMissilegreenMaridia": {"left": 1, "top": 7, "room": "cfc9", "variaArea": "WestMaridia"},
    "EnergyTankMamaturtle": {"left": 8, "top": 8, "room": "d055", "variaArea": "WestMaridia"},
    "MissilegreenMaridiatatori": {"left": 9, "top": 9, "room": "d055", "variaArea": "WestMaridia"},
    "SuperMissileyellowMaridia": {"left": 2, "top": 2, "room": "d13b", "variaArea": "WestMaridia"},
    "MissileyellowMaridiasupermissile": {"left": 2, "top": 2, "room": "d13b", "variaArea": "WestMaridia"},
    "MissileyellowMaridiafalsewall": {"left": 10, "top": 2, "room": "d1dd", "variaArea": "WestMaridia"},
    "PlasmaBeam": {"left": 10, "top": 5, "room": "d2aa", "variaArea": "EastMaridia"},
    "MissileleftMaridiasandpitroom": {"left": 2, "top": 17, "room": "d4ef", "variaArea": "EastMaridia"},
    "ReserveTankMaridia": {"left": 2, "top": 17, "room": "d4ef", "variaArea": "EastMaridia"},
    "MissilerightMaridiasandpitroom": {"left": 5, "top": 17, "room": "d51e", "variaArea": "EastMaridia"},
    "PowerBombrightMaridiasandpitroom": {"left": 6, "top": 18, "room": "d51e", "variaArea": "EastMaridia"},
    "MissilepinkMaridia": {"left": 6, "top": 12, "room": "d5a7", "variaArea": "EastMaridia"},
    "SuperMissilepinkMaridia": {"left": 7, "top": 12, "room": "d5a7", "variaArea": "EastMaridia"},
    "SpringBall": {"left": 15, "top": 19, "room": "d6d0", "variaArea": "EastMaridia"},
    "MissileDraygon": {"left": 24, "top": 10, "room": "d78f", "variaArea": "EastMaridia"},
    "EnergyTankBotwoon": {"left": 11, "top": 11, "room": "d7e4", "variaArea": "EastMaridia"},
    "SpaceJump": {"left": 0, "top": 1, "room": "d9aa", "variaArea": "Draygon"},
    "Kraid": {"left": 0.5, "top": 0.5, "room": "a59f", "variaArea": "Kraid"},
    "Phantoon": {"left": 0, "top": 0, "room": "cd13", "variaArea": "Phantoon"},
    "Draygon": {"left": 1.5, "top": 0.5, "room": "da60", "variaArea": "Draygon"},
    "Ridley": {"left": 1, "top": 0.5, "room": "b32e", "variaArea": "Ridley"},
    "MotherBrain": {"left": 2, "top": 10, "room": "dd58", "variaArea": "Tourian"},
    "SporeSpawn": {"left": 17, "top": 5, "room": "9dc7", "variaArea": "GreenBrinstar"},
    "Botwoon": {"left": 6, "top": 11, "room": "d95e", "variaArea": "EastMaridia"},
    "GoldenTorizo": {"left": 4, "top": 13, "room": "b283", "variaArea": "LowerNorfair"},
    "Crocomire": {"left": 13, "top": 0, "room": "a98d", "variaArea": "Crocomire"},
};
doors['vanilla'] = {
    "LandingSiteRight": {"left": 25, "top": 4, "facing": 0, "room": "91f8", "variaArea": "Crateria"},
    "LandingSiteTopRight": {"left": 25, "top": 1, "facing": 0, "room": "91f8", "variaArea": "Crateria"},
    "WestOceanRight": {"left": 7, "top": 4, "facing": 0, "room": "93fe", "variaArea": "WreckedShip"},
    "KihunterRight": {"left": 29, "top": 4, "facing": 0, "room": "948c", "variaArea": "Crateria"},
    "KihunterBottom": {"left": 28, "top": 6, "facing": 2, "room": "948c", "variaArea": "Crateria"},
    "LeCoudeBottom": {"left": 15, "top": 0, "facing": 2, "room": "95a8", "variaArea": "EastMaridia"},
    "RedBrinstarElevatorTop": {"left": 14, "top": 0, "facing": 3, "room": "962a", "variaArea": "RedBrinstar"},
    "ClimbRight": {"left": 14, "top": 16, "facing": 0, "room": "96ba", "variaArea": "Crateria"},
    "FlywayRight": {"left": 18, "top": 6, "facing": 0, "room": "9879", "variaArea": "Crateria"},
    "GreenPiratesShaftBottomRight": {"left": 5, "top": 8, "facing": 0, "room": "99bd", "variaArea": "Crateria"},
    "GreenBrinstarSaveStation": {"left": 4, "top": 7, "facing": 1, "room": "9ad9", "variaArea": "GreenBrinstar"},
    "MainShaftRight": {"left": 4, "top": 6, "facing": 0, "room": "9ad9", "variaArea": "GreenBrinstar"},
    "MainShaftBottomRight": {"left": 4, "top": 8, "facing": 0, "room": "9ad9", "variaArea": "GreenBrinstar"},
    "GreenBrinstarMissileRefill": {"left": 4, "top": 8, "facing": 1, "room": "9ad9", "variaArea": "GreenBrinstar"},
    "EarlySupersRight": {"left": 7, "top": 6, "facing": 0, "room": "9bc8", "variaArea": "GreenBrinstar"},
    "BigPinkRight": {"left": 13, "top": 10, "facing": 0, "room": "9d19", "variaArea": "GreenBrinstar"},
    "BigPinkBottomRight": {"left": 13, "top": 12, "facing": 0, "room": "9d19", "variaArea": "GreenBrinstar"},
    "BigPinkTopRight": {"left": 13, "top": 6, "facing": 0, "room": "9d19", "variaArea": "GreenBrinstar"},
    "BigPinkBottomLeft": {"left": 10, "top": 15, "facing": 1, "room": "9d19", "variaArea": "GreenBrinstar"},
    "GreenHillZoneTopRight": {"left": 15, "top": 12, "facing": 0, "room": "9e52", "variaArea": "GreenBrinstar"},
    "ConstructionZoneRight": {"left": 19, "top": 29, "facing": 0, "room": "9f11", "variaArea": "Crateria"},
    "NoobBridgeRight": {"left": 27, "top": 15, "facing": 0, "room": "9fba", "variaArea": "GreenBrinstar"},
    "EtecoonEnergyTankLeft": {"left": 1, "top": 12, "facing": 1, "room": "a011", "variaArea": "GreenBrinstar"},
    "RedBrinstarEnergyRefill": {"left": 10, "top": 16, "facing": 1, "room": "a253", "variaArea": "RedBrinstar"},
    "RedTowerLeft": {"left": 10, "top": 13, "facing": 1, "room": "a253", "variaArea": "RedBrinstar"},
    "RedBrinstarFirefleaLeft": {"left": 2, "top": 13, "facing": 1, "room": "a293", "variaArea": "RedBrinstar"},
    "RedTowerElevatorTopLeft": {"left": 14, "top": 5, "facing": 1, "room": "a322", "variaArea": "RedBrinstar"},
    "RedTowerElevatorLeft": {"left": 14, "top": 7, "facing": 1, "room": "a322", "variaArea": "RedBrinstar"},
    "RedTowerElevatorBottomLeft": {"left": 14, "top": 9, "facing": 1, "room": "a322", "variaArea": "RedBrinstar"},
    "BelowSpazerTopRight": {"left": 14, "top": 15, "facing": 0, "room": "a408", "variaArea": "RedBrinstar"},
    "KraidRefillStation": {"left": 10, "top": 0, "facing": 0, "room": "a56b", "variaArea": "KraidLair"},
    "CathedralRight": {"left": 14, "top": 6, "facing": 0, "room": "a788", "variaArea": "UpperNorfair"},
    "CathedralEntranceRight": {"left": 11, "top": 5, "facing": 0, "room": "a7b3", "variaArea": "UpperNorfair"},
    "BusinessCenterTopLeft": {"left": 8, "top": 5, "facing": 1, "room": "a7de", "variaArea": "UpperNorfair"},
    "BusinessCenterBottomLeft": {"left": 8, "top": 7, "facing": 1, "room": "a7de", "variaArea": "UpperNorfair"},
    "CrocomireSpeedwayBottom": {"left": 13, "top": 11, "facing": 2, "room": "a923", "variaArea": "UpperNorfair"},
    "PostCrocomireUpperLeft": {"left": 7, "top": 0, "facing": 1, "room": "aa82", "variaArea": "Crocomire"},
    "PostCrocomireShaftRight": {"left": 7, "top": 5, "facing": 0, "room": "ab07", "variaArea": "Crocomire"},
    "BubbleMountainTopLeft": {"left": 20, "top": 4, "facing": 1, "room": "acb3", "variaArea": "UpperNorfair"},
    "BubbleMountainTopRight": {"left": 21, "top": 4, "facing": 0, "room": "acb3", "variaArea": "UpperNorfair"},
    "SpeedBoosterHallRight": {"left": 34, "top": 4, "facing": 0, "room": "acf0", "variaArea": "UpperNorfair"},
    "SingleChamberRight": {"left": 22, "top": 6, "facing": 0, "room": "ad5e", "variaArea": "UpperNorfair"},
    "DoubleChamberRight": {"left": 26, "top": 6, "facing": 0, "room": "adad", "variaArea": "UpperNorfair"},
    "KronicBoostBottomLeft": {"left": 24, "top": 12, "facing": 1, "room": "ae74", "variaArea": "UpperNorfair"},
    "RedKihunterShaftBottom": {"left": 22, "top": 10, "facing": 2, "room": "b585", "variaArea": "LowerNorfair"},
    "WastelandLeft": {"left": 18, "top": 13, "facing": 1, "room": "b5d5", "variaArea": "LowerNorfair"},
    "WreckedShipMainShaftBottom": {"left": 12, "top": 8, "facing": 2, "room": "caf6", "variaArea": "WreckedShip"},
    "ElectricDeathRoomTopLeft": {"left": 17, "top": 3, "facing": 1, "room": "cbd5", "variaArea": "WreckedShip"},
    "MaridiaBottomSaveStation": {"left": 16, "top": 17, "facing": 0, "room": "cefb", "variaArea": "RedBrinstar"},
    "MainStreetBottomRight": {"left": 1, "top": 12, "facing": 0, "room": "cfc9", "variaArea": "WestMaridia"},
    "FishTankRight": {"left": 6, "top": 11, "facing": 0, "room": "d017", "variaArea": "WestMaridia"},
    "CrabShaftRight": {"left": 9, "top": 6, "facing": 0, "room": "d1a3", "variaArea": "WestMaridia"},
    "ForgottenHighwaySaveStation": {"left": 16, "top": 7, "facing": 0, "room": "d30b", "variaArea": "EastMaridia"},
    "PlasmaSparkBottom": {"left": 4, "top": 7, "facing": 2, "room": "d340", "variaArea": "EastMaridia"},
    "OasisTop": {"left": 4, "top": 18, "facing": 3, "room": "d48e", "variaArea": "EastMaridia"},
    "MaridiaAqueductSaveStation": {"left": 2, "top": 14, "facing": 1, "room": "d5a7", "variaArea": "EastMaridia"},
    "DraygonSaveRefillStation": {"left": 22, "top": 9, "facing": 0, "room": "d72a", "variaArea": "EastMaridia"},
    "ColosseumBottomRight": {"left": 22, "top": 10, "facing": 0, "room": "d72a", "variaArea": "EastMaridia"},
};
aps['vanilla'] = {
   "lowerMushroomsLeft": {"left": 1, "top": 8, "facing": 0, "room": "9969", "area": "Crateria", "type": "area"},
   "greenPiratesShaftBottomRight": {"left": 5, "top": 8, "facing": 1, "room": "99bd", "area": "Crateria", "type": "area"},
   "moatRight": {"left": 31, "top": 4, "facing": 1, "room": "95ff", "area": "Crateria", "type": "area"},
   "keyhunterRoomBottom": {"left": 28, "top": 6, "facing": 3, "room": "948c", "area": "Crateria", "type": "area"},
   "morphBallRoomLeft": {"left": 11, "top": 29, "facing": 0, "room": "9e9f", "area": "Crateria", "type": "area"},
   "greenBrinstarElevator": {"left": 4, "top": 0, "facing": 1, "room": "9938", "area": "GreenBrinstar", "type": "area"},
   "greenHillZoneTopRight": {"left": 15, "top": 12, "facing": 1, "room": "9e52", "area": "GreenBrinstar", "type": "area"},
   "noobBridgeRight": {"left": 27, "top": 15, "facing": 1, "room": "9fba", "area": "GreenBrinstar", "type": "area"},
   "westOceanLeft": {"left": 0, "top": 4, "facing": 0, "room": "93fe", "area": "WreckedShip", "type": "area"},
   "crabMazeLeft": {"left": 22, "top": 9, "facing": 0, "room": "957d", "area": "WreckedShip", "type": "area"},
   "lavaDiveRight": {"left": 10, "top": 7, "facing": 1, "room": "af14", "area": "LowerNorfair", "type": "area"},
   "threeMuskateersRoomLeft": {"left": 15, "top": 0, "facing": 0, "room": "b656", "area": "LowerNorfair", "type": "area"},
   "warehouseZeelaRoomLeft": {"left": 1, "top": 0, "facing": 0, "room": "a471", "area": "KraidLair", "type": "area"},
   "warehouseEntranceLeft": {"left": 8, "top": 0, "facing": 0, "room": "a6a1", "area": "UpperNorfair", "type": "area"},
   "warehouseEntranceRight": {"left": 10, "top": 0, "facing": 1, "room": "a6a1", "area": "UpperNorfair", "type": "area"},
   "singleChamberTopRight": {"left": 27, "top": 5, "facing": 1, "room": "ad5e", "area": "UpperNorfair", "type": "area"},
   "kronicBoostRoomBottomLeft": {"left": 24, "top": 12, "facing": 0, "room": "ae74", "area": "UpperNorfair", "type": "area"},
   "crocomireSpeedwayBottom": {"left": 13, "top": 11, "facing": 3, "room": "a923", "area": "UpperNorfair", "type": "area"},
   "crocomireRoomTop": {"left": 12, "top": 0, "facing": 2, "room": "a98d", "area": "Crocomire", "type": "area"},
   "mainStreetBottom": {"left": 1, "top": 12, "facing": 3, "room": "cfc9", "area": "WestMaridia", "type": "area"},
   "crabHoleBottomLeft": {"left": 6, "top": 13, "facing": 0, "room": "d21c", "area": "WestMaridia", "type": "area"},
   "redFishRoomLeft": {"left": 2, "top": 3, "facing": 0, "room": "d104", "area": "WestMaridia", "type": "area"},
   "crabShaftRight": {"left": 9, "top": 6, "facing": 1, "room": "d1a3", "area": "WestMaridia", "type": "area"},
   "aqueductTopLeft": {"left": 2, "top": 13, "facing": 0, "room": "d5a7", "area": "EastMaridia", "type": "area"},
   "leCoudeRight": {"left": 15, "top": 0, "facing": 1, "room": "95a8", "area": "EastMaridia", "type": "area"},
   "redTowerTopLeft": {"left": 10, "top": 11, "facing": 0, "room": "a253", "area": "RedBrinstar", "type": "area"},
   "caterpillarRoomTopRight": {"left": 16, "top": 5, "facing": 1, "room": "a322", "area": "RedBrinstar", "type": "area"},
   "redBrinstarElevator": {"left": 14, "top": 0, "facing": 2, "room": "962a", "area": "RedBrinstar", "type": "area"},
   "eastTunnelRight": {"left": 17, "top": 16, "facing": 1, "room": "cf80", "area": "RedBrinstar", "type": "area"},
   "eastTunnelTopRight": {"left": 20, "top": 15, "facing": 1, "room": "cf80", "area": "RedBrinstar", "type": "area"},
   "glassTunnelTop": {"left": 16, "top": 15, "facing": 2, "room": "cefb", "area": "RedBrinstar", "type": "area"},
   "goldenFour": {"left": 4, "top": 0, "facing": 0, "room": "a5ed", "area": "Tourian", "type": "area"},
   "phantoonRoomOut": {"left": 14, "top": 9, "facing": 1, "room": "cc6f", "area": "WreckedShip", "type": "boss"},
   "phantoonRoomIn": {"left": 0, "top": 0, "facing": 0, "room": "cd13", "area": "Phantoon", "type": "boss"},
   "ridleyRoomOut": {"left": 9, "top": 13, "facing": 0, "room": "b37a", "area": "LowerNorfair", "type": "boss"},
   "ridleyRoomIn": {"left": 1, "top": 0, "facing": 1, "room": "b32e", "area": "Ridley", "type": "boss"},
   "kraidRoomOut": {"left": 11, "top": 1, "facing": 1, "room": "a56b", "area": "KraidLair", "type": "boss"},
   "kraidRoomIn": {"left": 0, "top": 1, "facing": 0, "room": "a59f", "area": "Kraid", "type": "boss"},
   "draygonRoomOut": {"left": 23, "top": 12, "facing": 0, "room": "d78f", "area": "EastMaridia", "type": "boss"},
   "draygonRoomIn": {"left": 2, "top": 0, "facing": 1, "room": "da60", "area": "Draygon", "type": "boss"},
   "tourianEscapeRoom4TopRight": {"left": 9, "top": 9, "facing": 1, "room": "dede", "area": "Tourian", "type": "escape"},
   "climbBottomLeft": {"left": 12, "top": 17, "facing": 0, "room": "96ba", "area": "Crateria", "type": "escape"},
   "greenBrinstarMainShaftTopLeft": {"left": 4, "top": 6, "facing": 0, "room": "9ad9", "area": "GreenBrinstar", "type": "escape"},
   "basementLeft": {"left": 10, "top": 9, "facing": 0, "room": "cc6f", "area": "WreckedShip", "type": "escape"},
   "businessCenterMidLeft": {"left": 8, "top": 6, "facing": 0, "room": "a7de", "area": "UpperNorfair", "type": "escape"},
   "crabHoleBottomRight": {"left": 6, "top": 13, "facing": 1, "room": "d21c", "area": "WestMaridia", "type": "escape"},
};


locations['mirror'] = {
    "PowerBombCrateriasurface": {"left": 4, "top": 1, "room": "93aa", "variaArea": "Crateria"},
    "MissileoutsideWreckedShipbottom": {"left": 25, "top": 5, "room": "93fe", "variaArea": "WreckedShip"},
    "MissileoutsideWreckedShiptop": {"left": 24, "top": 0, "room": "93fe", "variaArea": "WreckedShip"},
    "MissileoutsideWreckedShipmiddle": {"left": 25, "top": 2, "room": "93fe", "variaArea": "WreckedShip"},
    "MissileCrateriamoat": {"left": 1, "top": 4, "room": "95ff", "variaArea": "Crateria"},
    "EnergyTankGauntlet": {"left": 20, "top": 2, "room": "965b", "variaArea": "Crateria"},
    "MissileCrateriabottom": {"left": 17, "top": 18, "room": "975c", "variaArea": "Crateria"},
    "Bomb": {"left": 12, "top": 6, "room": "9804", "variaArea": "Crateria"},
    "EnergyTankTerminator": {"left": 25, "top": 6, "room": "990d", "variaArea": "Crateria"},
    "MissileCrateriagauntletright": {"left": 26, "top": 3, "room": "99bd", "variaArea": "Crateria"},
    "MissileCrateriagauntletleft": {"left": 26, "top": 3, "room": "99bd", "variaArea": "Crateria"},
    "SuperMissileCrateria": {"left": 13, "top": 9, "room": "99f9", "variaArea": "Crateria"},
    "MissileCrateriamiddle": {"left": 21, "top": 7, "room": "9a90", "variaArea": "Crateria"},
    "PowerBombgreenBrinstarbottom": {"left": 20, "top": 9, "room": "9ad9", "variaArea": "GreenBrinstar"},
    "SuperMissilepinkBrinstar": {"left": 8, "top": 11, "room": "9b5b", "variaArea": "GreenBrinstar"},
    "MissilegreenBrinstarbelowsupermissile": {"left": 21, "top": 6, "room": "9bc8", "variaArea": "GreenBrinstar"},
    "SuperMissilegreenBrinstartop": {"left": 22, "top": 5, "room": "9bc8", "variaArea": "GreenBrinstar"},
    "ReserveTankBrinstar": {"left": 19, "top": 6, "room": "9c07", "variaArea": "GreenBrinstar"},
    "MissilegreenBrinstarbehindmissile": {"left": 18, "top": 6, "room": "9c07", "variaArea": "GreenBrinstar"},
    "MissilegreenBrinstarbehindreservetank": {"left": 18, "top": 6, "room": "9c07", "variaArea": "GreenBrinstar"},
    "MissilepinkBrinstartop": {"left": 15, "top": 9, "room": "9d19", "variaArea": "GreenBrinstar"},
    "MissilepinkBrinstarbottom": {"left": 15, "top": 12, "room": "9d19", "variaArea": "GreenBrinstar"},
    "ChargeBeam": {"left": 15, "top": 13, "room": "9d19", "variaArea": "GreenBrinstar"},
    "PowerBombpinkBrinstar": {"left": 17, "top": 10, "room": "9e11", "variaArea": "GreenBrinstar"},
    "MissilegreenBrinstarpipe": {"left": 10, "top": 13, "room": "9e52", "variaArea": "GreenBrinstar"},
    "MorphingBall": {"left": 15, "top": 29, "room": "9e9f", "variaArea": "Crateria"},
    "PowerBombblueBrinstar": {"left": 17, "top": 29, "room": "9e9f", "variaArea": "Crateria"},
    "MissileblueBrinstarmiddle": {"left": 8, "top": 29, "room": "9f64", "variaArea": "Crateria"},
    "EnergyTankBrinstarCeiling": {"left": 9, "top": 29, "room": "9f64", "variaArea": "Crateria"},
    "EnergyTankEtecoons": {"left": 26, "top": 12, "room": "a011", "variaArea": "GreenBrinstar"},
    "SuperMissilegreenBrinstarbottom": {"left": 27, "top": 12, "room": "a051", "variaArea": "GreenBrinstar"},
    "EnergyTankWaterway": {"left": 24, "top": 15, "room": "a0d2", "variaArea": "GreenBrinstar"},
    "MissileblueBrinstarbottom": {"left": 12, "top": 30, "room": "a107", "variaArea": "Crateria"},
    "EnergyTankBrinstarGate": {"left": 11, "top": 10, "room": "a15b", "variaArea": "GreenBrinstar"},
    "MissileblueBrinstartop": {"left": 11, "top": 27, "room": "a1d8", "variaArea": "Crateria"},
    "MissileblueBrinstarbehindmissile": {"left": 11, "top": 27, "room": "a1d8", "variaArea": "Crateria"},
    "XRayScope": {"left": 20, "top": 13, "room": "a2ce", "variaArea": "RedBrinstar"},
    "PowerBombredBrinstarsidehopperroom": {"left": 8, "top": 6, "room": "a37c", "variaArea": "RedBrinstar"},
    "PowerBombredBrinstarspikeroom": {"left": 8, "top": 9, "room": "a3ae", "variaArea": "RedBrinstar"},
    "MissileredBrinstarspikeroom": {"left": 9, "top": 9, "room": "a3ae", "variaArea": "RedBrinstar"},
    "Spazer": {"left": 5, "top": 15, "room": "a447", "variaArea": "RedBrinstar"},
    "EnergyTankKraid": {"left": 11, "top": 1, "room": "a4b1", "variaArea": "KraidLair"},
    "MissileKraid": {"left": 7, "top": 0, "room": "a4da", "variaArea": "KraidLair"},
    "VariaSuit": {"left": 0, "top": 1, "room": "a6e2", "variaArea": "Kraid"},
    "Missilelavaroom": {"left": 21, "top": 6, "room": "a788", "variaArea": "UpperNorfair"},
    "IceBeam": {"left": 32, "top": 4, "room": "a890", "variaArea": "UpperNorfair"},
    "MissilebelowIceBeam": {"left": 35, "top": 6, "room": "a8f8", "variaArea": "UpperNorfair"},
    "EnergyTankCrocomire": {"left": 0, "top": 0, "room": "a98d", "variaArea": "Crocomire"},
    "HiJumpBoots": {"left": 30, "top": 8, "room": "a9e5", "variaArea": "UpperNorfair"},
    "MissileaboveCrocomire": {"left": 26, "top": 8, "room": "aa0e", "variaArea": "UpperNorfair"},
    "MissileHiJumpBoots": {"left": 29, "top": 7, "room": "aa41", "variaArea": "UpperNorfair"},
    "EnergyTankHiJumpBoots": {"left": 28, "top": 7, "room": "aa41", "variaArea": "UpperNorfair"},
    "PowerBombCrocomire": {"left": 10, "top": 0, "room": "aade", "variaArea": "Crocomire"},
    "MissilebelowCrocomire": {"left": 5, "top": 5, "room": "ab3b", "variaArea": "Crocomire"},
    "MissileGrappleBeam": {"left": 11, "top": 5, "room": "ab8f", "variaArea": "Crocomire"},
    "GrappleBeam": {"left": 16, "top": 6, "room": "ac2b", "variaArea": "Crocomire"},
    "ReserveTankNorfair": {"left": 19, "top": 4, "room": "ac5a", "variaArea": "UpperNorfair"},
    "MissileNorfairReserveTank": {"left": 19, "top": 4, "room": "ac5a", "variaArea": "UpperNorfair"},
    "MissilebubbleNorfairgreendoor": {"left": 16, "top": 4, "room": "ac83", "variaArea": "UpperNorfair"},
    "MissilebubbleNorfair": {"left": 14, "top": 7, "room": "acb3", "variaArea": "UpperNorfair"},
    "MissileSpeedBooster": {"left": 1, "top": 4, "room": "acf0", "variaArea": "UpperNorfair"},
    "SpeedBooster": {"left": 0, "top": 4, "room": "ad1b", "variaArea": "UpperNorfair"},
    "MissileWaveBeam": {"left": 11, "top": 6, "room": "adad", "variaArea": "UpperNorfair"},
    "WaveBeam": {"left": 8, "top": 6, "room": "adde", "variaArea": "UpperNorfair"},
    "MissileGoldTorizo": {"left": 19, "top": 12, "room": "b283", "variaArea": "LowerNorfair"},
    "SuperMissileGoldTorizo": {"left": 18, "top": 12, "room": "b283", "variaArea": "LowerNorfair"},
    "MissileMickeyMouseroom": {"left": 9, "top": 7, "room": "b40a", "variaArea": "LowerNorfair"},
    "MissilelowerNorfairabovefireflearoom": {"left": 2, "top": 2, "room": "b510", "variaArea": "LowerNorfair"},
    "PowerBomblowerNorfairabovefireflearoom": {"left": 0, "top": 3, "room": "b55a", "variaArea": "LowerNorfair"},
    "PowerBombPowerBombsofshame": {"left": 5, "top": 11, "room": "b5d5", "variaArea": "LowerNorfair"},
    "MissilelowerNorfairnearWaveBeam": {"left": 8, "top": 2, "room": "b656", "variaArea": "LowerNorfair"},
    "EnergyTankRidley": {"left": 1, "top": 1, "room": "b698", "variaArea": "Ridley"},
    "ScrewAttack": {"left": 17, "top": 13, "room": "b6c1", "variaArea": "LowerNorfair"},
    "EnergyTankFirefleas": {"left": 0, "top": 8, "room": "b6ee", "variaArea": "LowerNorfair"},
    "ReserveTankWreckedShip": {"left": 14, "top": 1, "room": "c98e", "variaArea": "WreckedShip"},
    "MissileGravitySuit": {"left": 16, "top": 3, "room": "c98e", "variaArea": "WreckedShip"},
    "MissileWreckedShiptop": {"left": 8, "top": 0, "room": "caae", "variaArea": "WreckedShip"},
    "MissileWreckedShipmiddle": {"left": 17, "top": 6, "room": "caf6", "variaArea": "WreckedShip"},
    "EnergyTankWreckedShip": {"left": 11, "top": 3, "room": "cc27", "variaArea": "WreckedShip"},
    "SuperMissileWreckedShipleft": {"left": 14, "top": 7, "room": "cda8", "variaArea": "WreckedShip"},
    "RightSuperWreckedShip": {"left": 8, "top": 7, "room": "cdf1", "variaArea": "WreckedShip"},
    "GravitySuit": {"left": 19, "top": 3, "room": "ce40", "variaArea": "WreckedShip"},
    "MissilegreenMaridiashinespark": {"left": 11, "top": 8, "room": "cfc9", "variaArea": "WestMaridia"},
    "SuperMissilegreenMaridia": {"left": 10, "top": 7, "room": "cfc9", "variaArea": "WestMaridia"},
    "EnergyTankMamaturtle": {"left": 3, "top": 8, "room": "d055", "variaArea": "WestMaridia"},
    "MissilegreenMaridiatatori": {"left": 2, "top": 9, "room": "d055", "variaArea": "WestMaridia"},
    "SuperMissileyellowMaridia": {"left": 9, "top": 2, "room": "d13b", "variaArea": "WestMaridia"},
    "MissileyellowMaridiasupermissile": {"left": 9, "top": 2, "room": "d13b", "variaArea": "WestMaridia"},
    "MissileyellowMaridiafalsewall": {"left": 1, "top": 2, "room": "d1dd", "variaArea": "WestMaridia"},
    "PlasmaBeam": {"left": 14, "top": 5, "room": "d2aa", "variaArea": "EastMaridia"},
    "MissileleftMaridiasandpitroom": {"left": 22, "top": 17, "room": "d4ef", "variaArea": "EastMaridia"},
    "ReserveTankMaridia": {"left": 22, "top": 17, "room": "d4ef", "variaArea": "EastMaridia"},
    "MissilerightMaridiasandpitroom": {"left": 19, "top": 17, "room": "d51e", "variaArea": "EastMaridia"},
    "PowerBombrightMaridiasandpitroom": {"left": 18, "top": 18, "room": "d51e", "variaArea": "EastMaridia"},
    "MissilepinkMaridia": {"left": 18, "top": 12, "room": "d5a7", "variaArea": "EastMaridia"},
    "SuperMissilepinkMaridia": {"left": 17, "top": 12, "room": "d5a7", "variaArea": "EastMaridia"},
    "SpringBall": {"left": 9, "top": 19, "room": "d6d0", "variaArea": "EastMaridia"},
    "MissileDraygon": {"left": 0, "top": 10, "room": "d78f", "variaArea": "EastMaridia"},
    "EnergyTankBotwoon": {"left": 13, "top": 11, "room": "d7e4", "variaArea": "EastMaridia"},
    "SpaceJump": {"left": 1, "top": 1, "room": "d9aa", "variaArea": "Draygon"},
    "Kraid": {"left": 1, "top": 5, "room": "a59f", "variaArea": "Kraid"},
    "Phantoon": {"left": 0, "top": 0, "room": "cd13", "variaArea": "Phantoon"},
    "Draygon": {"left": 0.5, "top": 0.5, "room": "da60", "variaArea": "Draygon"},
    "Ridley": {"left": 0, "top": 0.5, "room": "b32e", "variaArea": "Ridley"},
    "MotherBrain": {"left": 8, "top": 10, "room": "fd40", "variaArea": "Tourian"},
    "SporeSpawn": {"left": 10, "top": 5, "room": "9dc7", "variaArea": "GreenBrinstar"},
    "Botwoon": {"left": 17, "top": 11, "room": "d95e", "variaArea": "EastMaridia"},
    "GoldenTorizo": {"left": 20, "top": 13, "room": "b283", "variaArea": "LowerNorfair"},
    "Crocomire": {"left": 5, "top": 0, "room": "a98d", "variaArea": "Crocomire"},
};
doors['mirror'] = {
    "LandingSiteRight": {"left": 6, "top": 4, "facing": 1, "room": "91f8", "variaArea": "Crateria"},
    "LandingSiteTopRight": {"left": 6, "top": 1, "facing": 1, "room": "91f8", "variaArea": "Crateria"},
    "WestOceanRight": {"left": 18, "top": 4, "facing": 1, "room": "93fe", "variaArea": "WreckedShip"},
    "KihunterRight": {"left": 2, "top": 4, "facing": 1, "room": "948c", "variaArea": "Crateria"},
    "KihunterBottom": {"left": 3, "top": 6, "facing": 2, "room": "948c", "variaArea": "Crateria"},
    "LeCoudeBottom": {"left": 8, "top": 0, "facing": 2, "room": "95a8", "variaArea": "EastMaridia"},
    "RedBrinstarElevatorTop": {"left": 6, "top": 0, "facing": 3, "room": "962a", "variaArea": "RedBrinstar"},
    "ClimbRight": {"left": 17, "top": 16, "facing": 1, "room": "96ba", "variaArea": "Crateria"},
    "FlywayRight": {"left": 13, "top": 6, "facing": 1, "room": "9879", "variaArea": "Crateria"},
    "GreenPiratesShaftBottomRight": {"left": 26, "top": 8, "facing": 1, "room": "99bd", "variaArea": "Crateria"},
    "GreenBrinstarSaveStation": {"left": 23, "top": 7, "facing": 0, "room": "9ad9", "variaArea": "GreenBrinstar"},
    "MainShaftRight": {"left": 23, "top": 6, "facing": 1, "room": "9ad9", "variaArea": "GreenBrinstar"},
    "GreenBrinstarMissileRefill": {"left": 23, "top": 8, "facing": 0, "room": "9ad9", "variaArea": "GreenBrinstar"},
    "MainShaftBottomRight": {"left": 23, "top": 8, "facing": 1, "room": "9ad9", "variaArea": "GreenBrinstar"},
    "EarlySupersRight": {"left": 20, "top": 6, "facing": 1, "room": "9bc8", "variaArea": "GreenBrinstar"},
    "BigPinkRight": {"left": 14, "top": 10, "facing": 1, "room": "9d19", "variaArea": "GreenBrinstar"},
    "BigPinkBottomRight": {"left": 14, "top": 12, "facing": 1, "room": "9d19", "variaArea": "GreenBrinstar"},
    "BigPinkTopRight": {"left": 14, "top": 6, "facing": 1, "room": "9d19", "variaArea": "GreenBrinstar"},
    "BigPinkBottomLeft": {"left": 17, "top": 15, "facing": 0, "room": "9d19", "variaArea": "GreenBrinstar"},
    "GreenHillZoneTopRight": {"left": 12, "top": 12, "facing": 1, "room": "9e52", "variaArea": "GreenBrinstar"},
    "ConstructionZoneRight": {"left": 11, "top": 29, "facing": 1, "room": "9f11", "variaArea": "Crateria"},
    "NoobBridgeRight": {"left": 0, "top": 15, "facing": 1, "room": "9fba", "variaArea": "GreenBrinstar"},
    "EtecoonEnergyTankLeft": {"left": 26, "top": 12, "facing": 0, "room": "a011", "variaArea": "GreenBrinstar"},
    "RedBrinstarEnergyRefill": {"left": 10, "top": 16, "facing": 0, "room": "a253", "variaArea": "RedBrinstar"},
    "RedTowerLeft": {"left": 10, "top": 13, "facing": 0, "room": "a253", "variaArea": "RedBrinstar"},
    "RedBrinstarFirefleaLeft": {"left": 18, "top": 13, "facing": 0, "room": "a293", "variaArea": "RedBrinstar"},
    "RedTowerElevatorTopLeft": {"left": 6, "top": 5, "facing": 0, "room": "a322", "variaArea": "RedBrinstar"},
    "RedTowerElevatorLeft": {"left": 6, "top": 7, "facing": 0, "room": "a322", "variaArea": "RedBrinstar"},
    "RedTowerElevatorBottomLeft": {"left": 6, "top": 9, "facing": 0, "room": "a322", "variaArea": "RedBrinstar"},
    "BelowSpazerTopRight": {"left": 6, "top": 15, "facing": 1, "room": "a408", "variaArea": "RedBrinstar"},
    "KraidRefillStation": {"left": 1, "top": 0, "facing": 1, "room": "a56b", "variaArea": "KraidLair"},
    "CathedralRight": {"left": 21, "top": 6, "facing": 1, "room": "a788", "variaArea": "UpperNorfair"},
    "CathedralEntranceRight": {"left": 24, "top": 5, "facing": 1, "room": "a7b3", "variaArea": "UpperNorfair"},
    "BusinessCenterTopLeft": {"left": 27, "top": 5, "facing": 0, "room": "a7de", "variaArea": "UpperNorfair"},
    "BusinessCenterBottomLeft": {"left": 27, "top": 7, "facing": 0, "room": "a7de", "variaArea": "UpperNorfair"},
    "CrocomireSpeedwayBottom": {"left": 22, "top": 11, "facing": 2, "room": "a923", "variaArea": "UpperNorfair"},
    "PostCrocomireUpperLeft": {"left": 9, "top": 0, "facing": 0, "room": "aa82", "variaArea": "Crocomire"},
    "PostCrocomireShaftRight": {"left": 9, "top": 5, "facing": 1, "room": "ab07", "variaArea": "Crocomire"},
    "BubbleMountainTopLeft": {"left": 14, "top": 4, "facing": 1, "room": "acb3", "variaArea": "UpperNorfair"},
    "BubbleMountainTopRight": {"left": 15, "top": 4, "facing": 0, "room": "acb3", "variaArea": "UpperNorfair"},
    "SpeedBoosterHallRight": {"left": 1, "top": 4, "facing": 1, "room": "acf0", "variaArea": "UpperNorfair"},
    "SingleChamberRight": {"left": 13, "top": 6, "facing": 1, "room": "ad5e", "variaArea": "UpperNorfair"},
    "DoubleChamberRight": {"left": 9, "top": 6, "facing": 1, "room": "adad", "variaArea": "UpperNorfair"},
    "KronicBoostBottomLeft": {"left": 11, "top": 12, "facing": 0, "room": "ae74", "variaArea": "UpperNorfair"},
    "RedKihunterShaftBottom": {"left": 0, "top": 10, "facing": 2, "room": "b585", "variaArea": "LowerNorfair"},
    "WastelandLeft": {"left": 4, "top": 13, "facing": 0, "room": "b5d5", "variaArea": "LowerNorfair"},
    "WreckedShipMainShaftBottom": {"left": 13, "top": 8, "facing": 2, "room": "caf6", "variaArea": "WreckedShip"},
    "ElectricDeathRoomTopLeft": {"left": 8, "top": 3, "facing": 0, "room": "cbd5", "variaArea": "WreckedShip"},
    "MaridiaBottomSaveStation": {"left": 4, "top": 17, "facing": 1, "room": "cefb", "variaArea": "RedBrinstar"},
    "MainStreetBottomRight": {"left": 10, "top": 12, "facing": 1, "room": "cfc9", "variaArea": "WestMaridia"},
    "FishTankRight": {"left": 5, "top": 11, "facing": 1, "room": "d017", "variaArea": "WestMaridia"},
    "CrabShaftRight": {"left": 2, "top": 6, "facing": 1, "room": "d1a3", "variaArea": "WestMaridia"},
    "ForgottenHighwaySaveStation": {"left": 8, "top": 7, "facing": 1, "room": "d30b", "variaArea": "EastMaridia"},
    "PlasmaSparkBottom": {"left": 20, "top": 7, "facing": 2, "room": "d340", "variaArea": "EastMaridia"},
    "OasisTop": {"left": 20, "top": 18, "facing": 3, "room": "d48e", "variaArea": "EastMaridia"},
    "MaridiaAqueductSaveStation": {"left": 22, "top": 14, "facing": 0, "room": "d5a7", "variaArea": "EastMaridia"},
    "DraygonSaveRefillStation": {"left": 2, "top": 9, "facing": 1, "room": "d72a", "variaArea": "EastMaridia"},
    "ColosseumBottomRight": {"left": 2, "top": 10, "facing": 1, "room": "d72a", "variaArea": "EastMaridia"},
};
aps['mirror'] = {
   "lowerMushroomsLeft": {"left": 30, "top": 8, "facing": 1, "room": "9969", "area": "Crateria", "type": "area"},
   "greenPiratesShaftBottomRight": {"left": 26, "top": 8, "facing": 0, "room": "99bd", "area": "Crateria", "type": "area"},
   "moatRight": {"left": 0, "top": 4, "facing": 0, "room": "95ff", "area": "Crateria", "type": "area"},
   "keyhunterRoomBottom": {"left": 3, "top": 6, "facing": 3, "room": "948c", "area": "Crateria", "type": "area"},
   "morphBallRoomLeft": {"left": 19, "top": 29, "facing": 1, "room": "9e9f", "area": "Crateria", "type": "area"},
   "greenBrinstarElevator": {"left": 23, "top": 0, "facing": 0, "room": "9938", "area": "GreenBrinstar", "type": "area"},
   "greenHillZoneTopRight": {"left": 12, "top": 12, "facing": 0, "room": "9e52", "area": "GreenBrinstar", "type": "area"},
   "noobBridgeRight": {"left": 0, "top": 15, "facing": 0, "room": "9fba", "area": "GreenBrinstar", "type": "area"},
   "westOceanLeft": {"left": 25, "top": 4, "facing": 1, "room": "93fe", "area": "WreckedShip", "type": "area"},
   "crabMazeLeft": {"left": 3, "top": 9, "facing": 1, "room": "957d", "area": "WreckedShip", "type": "area"},
   "lavaDiveRight": {"left": 12, "top": 7, "facing": 0, "room": "af14", "area": "LowerNorfair", "type": "area"},
   "threeMuskateersRoomLeft": {"left": 7, "top": 0, "facing": 1, "room": "b656", "area": "LowerNorfair", "type": "area"},
   "warehouseZeelaRoomLeft": {"left": 10, "top": 0, "facing": 1, "room": "a471", "area": "KraidLair", "type": "area"},
   "warehouseEntranceLeft": {"left": 27, "top": 0, "facing": 1, "room": "a6a1", "area": "UpperNorfair", "type": "area"},
   "warehouseEntranceRight": {"left": 25, "top": 0, "facing": 0, "room": "a6a1", "area": "UpperNorfair", "type": "area"},
   "singleChamberTopRight": {"left": 8, "top": 5, "facing": 0, "room": "ad5e", "area": "UpperNorfair", "type": "area"},
   "kronicBoostRoomBottomLeft": {"left": 11, "top": 12, "facing": 1, "room": "ae74", "area": "UpperNorfair", "type": "area"},
   "crocomireSpeedwayBottom": {"left": 22, "top": 11, "facing": 3, "room": "a923", "area": "UpperNorfair", "type": "area"},
   "crocomireRoomTop": {"left": 3, "top": 0, "facing": 2, "room": "a98d", "area": "Crocomire", "type": "area"},
   "mainStreetBottom": {"left": 10, "top": 12, "facing": 3, "room": "cfc9", "area": "WestMaridia", "type": "area"},
   "crabHoleBottomLeft": {"left": 5, "top": 13, "facing": 1, "room": "d21c", "area": "WestMaridia", "type": "area"},
   "redFishRoomLeft": {"left": 9, "top": 3, "facing": 1, "room": "d104", "area": "WestMaridia", "type": "area"},
   "crabShaftRight": {"left": 2, "top": 6, "facing": 0, "room": "d1a3", "area": "WestMaridia", "type": "area"},
   "aqueductTopLeft": {"left": 22, "top": 13, "facing": 1, "room": "d5a7", "area": "EastMaridia", "type": "area"},
   "leCoudeRight": {"left": 8, "top": 0, "facing": 0, "room": "95a8", "area": "EastMaridia", "type": "area"},
   "redTowerTopLeft": {"left": 10, "top": 11, "facing": 1, "room": "a253", "area": "RedBrinstar", "type": "area"},
   "caterpillarRoomTopRight": {"left": 4, "top": 5, "facing": 0, "room": "a322", "area": "RedBrinstar", "type": "area"},
   "redBrinstarElevator": {"left": 6, "top": 0, "facing": 2, "room": "962a", "area": "RedBrinstar", "type": "area"},
   "eastTunnelRight": {"left": 3, "top": 16, "facing": 0, "room": "cf80", "area": "RedBrinstar", "type": "area"},
   "eastTunnelTopRight": {"left": 0, "top": 15, "facing": 0, "room": "cf80", "area": "RedBrinstar", "type": "area"},
   "glassTunnelTop": {"left": 4, "top": 15, "facing": 2, "room": "cefb", "area": "RedBrinstar", "type": "area"},
   "goldenFour": {"left": 6, "top": 0, "facing": 1, "room": "a5ed", "area": "Tourian", "type": "area"},
   "phantoonRoomOut": {"left": 11, "top": 9, "facing": 0, "room": "cc6f", "area": "WreckedShip", "type": "boss"},
   "phantoonRoomIn": {"left": 0, "top": 0, "facing": 1, "room": "cd13", "area": "Phantoon", "type": "boss"},
   "ridleyRoomOut": {"left": 13, "top": 13, "facing": 1, "room": "b37a", "area": "LowerNorfair", "type": "boss"},
   "ridleyRoomIn": {"left": 0, "top": 0, "facing": 0, "room": "b32e", "area": "Ridley", "type": "boss"},
   "kraidRoomOut": {"left": 0, "top": 1, "facing": 0, "room": "a56b", "area": "KraidLair", "type": "boss"},
   "kraidRoomIn": {"left": 2, "top": 1, "facing": 1, "room": "a59f", "area": "Kraid", "type": "boss"},
   "draygonRoomOut": {"left": 1, "top": 12, "facing": 1, "room": "d78f", "area": "EastMaridia", "type": "boss"},
   "draygonRoomIn": {"left": -1, "top": 0, "facing": 0, "room": "da60", "area": "Draygon", "type": "boss"},
   "tourianEscapeRoom4TopRight": {"left": 1, "top": 9, "facing": 0, "room": "dede", "area": "Tourian", "type": "escape"},
   "climbBottomLeft": {"left": 19, "top": 17, "facing": 1, "room": "96ba", "area": "Crateria", "type": "escape"},
   "greenBrinstarMainShaftTopLeft": {"left": 23, "top": 6, "facing": 1, "room": "9ad9", "area": "GreenBrinstar", "type": "escape"},
   "basementLeft": {"left": 15, "top": 9, "facing": 1, "room": "cc6f", "area": "WreckedShip", "type": "escape"},
   "businessCenterMidLeft": {"left": 27, "top": 6, "facing": 1, "room": "a7de", "area": "UpperNorfair", "type": "escape"},
   "crabHoleBottomRight": {"left": 5, "top": 13, "facing": 0, "room": "d21c", "area": "WestMaridia", "type": "escape"},
};
