-- store statistics about item placements

create table if not exists extended_stats (
  -- uniq identifier for join with item_locs
  id int unsigned not null auto_increment,
  -- the current version of the randomizer algorithm
  version int unsigned not null,
  -- randomizer parameters
  preset varchar(32),
  area boolean,
  boss boolean,
  majorsSplit varchar(8),
  progSpeed varchar(8),
  morphPlacement varchar(8),
  suitsRestriction boolean,
  progDiff varchar(8),
  superFunMovement boolean,
  superFunCombat boolean,
  superFunSuit boolean,
  -- how many seeds
  count int unsigned default 0,
  primary key(version, preset, area, boss, majorsSplit, progSpeed, morphPlacement, suitsRestriction, progDiff, superFunMovement, superFunCombat, superFunSuit),
  index(id)
);

create table if not exists item_locs (
  -- to join with extend_stats
  ext_id int unsigned not null,
  -- item
  item varchar(16) not null,
  -- locations (count how time the item has been placed at each location)
  EnergyTankGauntlet  mediumint unsigned default 0,
  Bomb  mediumint unsigned default 0,
  EnergyTankTerminator  mediumint unsigned default 0,
  ReserveTankBrinstar  mediumint unsigned default 0,
  ChargeBeam  mediumint unsigned default 0,
  MorphingBall  mediumint unsigned default 0,
  EnergyTankBrinstarCeiling  mediumint unsigned default 0,
  EnergyTankEtecoons  mediumint unsigned default 0,
  EnergyTankWaterway  mediumint unsigned default 0,
  EnergyTankBrinstarGate  mediumint unsigned default 0,
  XRayScope  mediumint unsigned default 0,
  Spazer  mediumint unsigned default 0,
  EnergyTankKraid  mediumint unsigned default 0,
  Kraid  mediumint unsigned default 0,
  VariaSuit  mediumint unsigned default 0,
  IceBeam  mediumint unsigned default 0,
  EnergyTankCrocomire  mediumint unsigned default 0,
  HiJumpBoots  mediumint unsigned default 0,
  GrappleBeam  mediumint unsigned default 0,
  ReserveTankNorfair  mediumint unsigned default 0,
  SpeedBooster  mediumint unsigned default 0,
  WaveBeam  mediumint unsigned default 0,
  Ridley  mediumint unsigned default 0,
  EnergyTankRidley  mediumint unsigned default 0,
  ScrewAttack  mediumint unsigned default 0,
  EnergyTankFirefleas  mediumint unsigned default 0,
  ReserveTankWreckedShip  mediumint unsigned default 0,
  EnergyTankWreckedShip  mediumint unsigned default 0,
  Phantoon  mediumint unsigned default 0,
  RightSuperWreckedShip  mediumint unsigned default 0,
  GravitySuit  mediumint unsigned default 0,
  EnergyTankMamaturtle  mediumint unsigned default 0,
  PlasmaBeam  mediumint unsigned default 0,
  ReserveTankMaridia  mediumint unsigned default 0,
  SpringBall  mediumint unsigned default 0,
  EnergyTankBotwoon  mediumint unsigned default 0,
  Draygon  mediumint unsigned default 0,
  SpaceJump  mediumint unsigned default 0,
  MotherBrain  mediumint unsigned default 0,
  PowerBombCrateriasurface  mediumint unsigned default 0,
  MissileoutsideWreckedShipbottom  mediumint unsigned default 0,
  MissileoutsideWreckedShiptop  mediumint unsigned default 0,
  MissileoutsideWreckedShipmiddle  mediumint unsigned default 0,
  MissileCrateriamoat  mediumint unsigned default 0,
  MissileCrateriabottom  mediumint unsigned default 0,
  MissileCrateriagauntletright  mediumint unsigned default 0,
  MissileCrateriagauntletleft  mediumint unsigned default 0,
  SuperMissileCrateria  mediumint unsigned default 0,
  MissileCrateriamiddle  mediumint unsigned default 0,
  PowerBombgreenBrinstarbottom  mediumint unsigned default 0,
  SuperMissilepinkBrinstar  mediumint unsigned default 0,
  MissilegreenBrinstarbelowsupermissile  mediumint unsigned default 0,
  SuperMissilegreenBrinstartop  mediumint unsigned default 0,
  MissilegreenBrinstarbehindmissile  mediumint unsigned default 0,
  MissilegreenBrinstarbehindreservetank  mediumint unsigned default 0,
  MissilepinkBrinstartop  mediumint unsigned default 0,
  MissilepinkBrinstarbottom  mediumint unsigned default 0,
  PowerBombpinkBrinstar  mediumint unsigned default 0,
  MissilegreenBrinstarpipe  mediumint unsigned default 0,
  PowerBombblueBrinstar  mediumint unsigned default 0,
  MissileblueBrinstarmiddle  mediumint unsigned default 0,
  SuperMissilegreenBrinstarbottom  mediumint unsigned default 0,
  MissileblueBrinstarbottom  mediumint unsigned default 0,
  MissileblueBrinstartop  mediumint unsigned default 0,
  MissileblueBrinstarbehindmissile  mediumint unsigned default 0,
  PowerBombredBrinstarsidehopperroom  mediumint unsigned default 0,
  PowerBombredBrinstarspikeroom  mediumint unsigned default 0,
  MissileredBrinstarspikeroom  mediumint unsigned default 0,
  MissileKraid  mediumint unsigned default 0,
  Missilelavaroom  mediumint unsigned default 0,
  MissilebelowIceBeam  mediumint unsigned default 0,
  MissileaboveCrocomire  mediumint unsigned default 0,
  MissileHiJumpBoots  mediumint unsigned default 0,
  EnergyTankHiJumpBoots  mediumint unsigned default 0,
  PowerBombCrocomire  mediumint unsigned default 0,
  MissilebelowCrocomire  mediumint unsigned default 0,
  MissileGrappleBeam  mediumint unsigned default 0,
  MissileNorfairReserveTank  mediumint unsigned default 0,
  MissilebubbleNorfairgreendoor  mediumint unsigned default 0,
  MissilebubbleNorfair  mediumint unsigned default 0,
  MissileSpeedBooster  mediumint unsigned default 0,
  MissileWaveBeam  mediumint unsigned default 0,
  MissileGoldTorizo  mediumint unsigned default 0,
  SuperMissileGoldTorizo  mediumint unsigned default 0,
  MissileMickeyMouseroom  mediumint unsigned default 0,
  MissilelowerNorfairabovefireflearoom  mediumint unsigned default 0,
  PowerBomblowerNorfairabovefireflearoom  mediumint unsigned default 0,
  PowerBombPowerBombsofshame  mediumint unsigned default 0,
  MissilelowerNorfairnearWaveBeam  mediumint unsigned default 0,
  MissileWreckedShipmiddle  mediumint unsigned default 0,
  MissileGravitySuit  mediumint unsigned default 0,
  MissileWreckedShiptop  mediumint unsigned default 0,
  SuperMissileWreckedShipleft  mediumint unsigned default 0,
  MissilegreenMaridiashinespark  mediumint unsigned default 0,
  SuperMissilegreenMaridia  mediumint unsigned default 0,
  MissilegreenMaridiatatori  mediumint unsigned default 0,
  SuperMissileyellowMaridia  mediumint unsigned default 0,
  MissileyellowMaridiasupermissile  mediumint unsigned default 0,
  MissileyellowMaridiafalsewall  mediumint unsigned default 0,
  MissileleftMaridiasandpitroom  mediumint unsigned default 0,
  MissilerightMaridiasandpitroom  mediumint unsigned default 0,
  PowerBombrightMaridiasandpitroom  mediumint unsigned default 0,
  MissilepinkMaridia  mediumint unsigned default 0,
  SuperMissilepinkMaridia  mediumint unsigned default 0,
  MissileDraygon  mediumint unsigned default 0,
  primary key(ext_id, item)
);

