rooms = [
{"Address": 0x0791F8, "DoorCount": 4, "Name": "Landing Site"},
{"Address": 0x0792B3, "DoorCount": 2, "Name": "Gauntlet Entrance"},
{"Address": 0x0792FD, "DoorCount": 7, "Name": "Parlor and Alcatraz"},
{"Address": 0x0793AA, "DoorCount": 1, "Name": "Crateria Power Bomb Room"},
{"Address": 0x0793D5, "DoorCount": 1, "Name": "[Parlor Save Room]"},
{"Address": 0x0793FE, "DoorCount": 6, "Name": "West Ocean"},
{"Address": 0x079461, "DoorCount": 2, "Name": "Bowling Alley Path"},
{"Address": 0x07948C, "DoorCount": 3, "Name": "Crateria Keyhunter Room"},
{"Address": 0x0794CC, "DoorCount": 3, "Name": "[Elevator to Maridia]"},
{"Address": 0x0794FD, "DoorCount": 2, "Name": "East Ocean"},
{"Address": 0x079552, "DoorCount": 2, "Name": "Forgotten Highway Kago Room"},
{"Address": 0x07957D, "DoorCount": 2, "Name": "Crab Maze"},
{"Address": 0x0795A8, "DoorCount": 2, "Name": "[Crab Maze to Elevator]"},
{"Address": 0x0795D4, "DoorCount": 2, "Name": "Crateria Tube"},
{"Address": 0x0795FF, "DoorCount": 2, "Name": "The Moat"},
{"Address": 0x07962A, "DoorCount": 3, "Name": "[Elevator to Red Brinstar]"},
{"Address": 0x07965B, "DoorCount": 2, "Name": "Gauntlet Energy Tank Room"},
{"Address": 0x07968F, "DoorCount": 2, "Name": "[West Ocean Geemer Corridor]"},
{"Address": 0x0796BA, "DoorCount": 5, "Name": "Climb"},
{"Address": 0x07975C, "DoorCount": 2, "Name": "Pit Room [Old Mother Brain Room]"},
{"Address": 0x0797B5, "DoorCount": 3, "Name": "[Elevator to Blue Brinstar]"},
{"Address": 0x079804, "DoorCount": 1, "Name": "Bomb Torizo Room"},
{"Address": 0x079879, "DoorCount": 2, "Name": "Flyway"},
{"Address": 0x0798E2, "DoorCount": 2, "Name": "Pre-Map Flyway"},
{"Address": 0x07990D, "DoorCount": 2, "Name": "Terminator Room"},
{"Address": 0x079938, "DoorCount": 3, "Name": "[Elevator to Green Brinstar]"},
{"Address": 0x079969, "DoorCount": 2, "Name": "Lower Mushrooms"},
{"Address": 0x079994, "DoorCount": 1, "Name": "Crateria Map Room"},
{"Address": 0x0799BD, "DoorCount": 4, "Name": "Green Pirates Shaft"},
{"Address": 0x0799F9, "DoorCount": 2, "Name": "Crateria Super Room"},
{"Address": 0x079A44, "DoorCount": 2, "Name": "Final Missile Bombway"},
{"Address": 0x079A90, "DoorCount": 1, "Name": "The Final Missile"},
{"Address": 0x07A5ED, "DoorCount": 2, "Name": "Statues Hallway"},
{"Address": 0x07A66A, "DoorCount": 3, "Name": "Statues Room"},
{"Address": 0x079AD9, "DoorCount": 11, "Name": "Green Brinstar Main Shaft [etecoon room]"},
{"Address": 0x079B5B, "DoorCount": 2, "Name": "Spore Spawn Super Room"},
{"Address": 0x079B9D, "DoorCount": 2, "Name": "Brinstar Pre-Map Room"},
{"Address": 0x079BC8, "DoorCount": 2, "Name": "Early Supers Room"},
{"Address": 0x079C07, "DoorCount": 1, "Name": "Brinstar Reserve Tank Room"},
{"Address": 0x079C35, "DoorCount": 1, "Name": "Brinstar Map Room"},
{"Address": 0x079C5E, "DoorCount": 2, "Name": "Green Brinstar Fireflea Room"},
{"Address": 0x079C89, "DoorCount": 1, "Name": "[Green Brinstar Missile Station]"},
{"Address": 0x079CB3, "DoorCount": 3, "Name": "Dachora Room"},
{"Address": 0x079D19, "DoorCount": 9, "Name": "Big Pink"},
{"Address": 0x079D9C, "DoorCount": 2, "Name": "Spore Spawn Keyhunter Room"},
{"Address": 0x079DC7, "DoorCount": 2, "Name": "Spore Spawn Room"},
{"Address": 0x079E11, "DoorCount": 2, "Name": "Pink Brinstar Power Bomb Room"},
{"Address": 0x079E52, "DoorCount": 3, "Name": "Green Hill Zone"},
{"Address": 0x079E9F, "DoorCount": 4, "Name": "Morph Ball Room"},
{"Address": 0x079F11, "DoorCount": 3, "Name": "Construction Zone"},
{"Address": 0x079F64, "DoorCount": 2, "Name": "Blue Brinstar Energy Tank Room"},
{"Address": 0x079FBA, "DoorCount": 2, "Name": "Noob Bridge"},
{"Address": 0x079FE5, "DoorCount": 2, "Name": "Green Brinstar Beetom Room"},
{"Address": 0x07A011, "DoorCount": 4, "Name": "Etecoon Energy Tank Room"},
{"Address": 0x07A051, "DoorCount": 1, "Name": "Etecoon Super Room"},
{"Address": 0x07A07B, "DoorCount": 1, "Name": "[Dachora Room Energy Charge Station]"},
{"Address": 0x07A0A4, "DoorCount": 2, "Name": "Spore Spawn Farming Room"},
{"Address": 0x07A0D2, "DoorCount": 1, "Name": "Waterway Energy Tank Room"},
{"Address": 0x07A107, "DoorCount": 1, "Name": "First Missile Room"},
{"Address": 0x07A130, "DoorCount": 2, "Name": "Pink Brinstar Hopper Room"},
{"Address": 0x07A15B, "DoorCount": 1, "Name": "Hopper Energy Tank Room"},
{"Address": 0x07A184, "DoorCount": 1, "Name": "[Spore Spawn Save Room]"},
{"Address": 0x07A1AD, "DoorCount": 2, "Name": "Blue Brinstar Boulder Room"},
{"Address": 0x07A1D8, "DoorCount": 1, "Name": "Blue Brinstar Double Missile Room"},
{"Address": 0x07A201, "DoorCount": 1, "Name": "[Green Brinstar Main Shaft Save Room]"},
{"Address": 0x07A22A, "DoorCount": 1, "Name": "[Etecoon Save Room]"},
{"Address": 0x07A253, "DoorCount": 5, "Name": "Red Tower"},
{"Address": 0x07A293, "DoorCount": 2, "Name": "Red Brinstar Fireflea Room"},
{"Address": 0x07A2CE, "DoorCount": 1, "Name": "X-Ray Scope Room"},
{"Address": 0x07A2F7, "DoorCount": 2, "Name": "Hellway"},
{"Address": 0x07A322, "DoorCount": 7, "Name": "Caterpillar Room"},
{"Address": 0x07A37C, "DoorCount": 1, "Name": "Beta Power Bomb Room"},
{"Address": 0x07A3AE, "DoorCount": 1, "Name": "Alpha Power Bomb Room"},
{"Address": 0x07A3DD, "DoorCount": 2, "Name": "Bat Room"},
{"Address": 0x07A408, "DoorCount": 3, "Name": "Below Spazer"},
{"Address": 0x07A447, "DoorCount": 1, "Name": "Spazer Room"},
{"Address": 0x07A471, "DoorCount": 3, "Name": "Warehouse Zeela Room"},
{"Address": 0x07A4B1, "DoorCount": 1, "Name": "Warehouse Energy Tank Room"},
{"Address": 0x07A4DA, "DoorCount": 3, "Name": "Warehouse Keyhunter Room"},
{"Address": 0x07A521, "DoorCount": 2, "Name": "Baby Kraid Room"},
{"Address": 0x07A56B, "DoorCount": 3, "Name": "Kraid Eye Door Room"},
{"Address": 0x07A59F, "DoorCount": 2, "Name": "Kraid Room"},
{"Address": 0x07A618, "DoorCount": 1, "Name": "[Red Tower Energy Charge Station]"},
{"Address": 0x07A641, "DoorCount": 1, "Name": "[Kraid Recharge Station]"},
{"Address": 0x07A6A1, "DoorCount": 4, "Name": "Warehouse Entrance"},
{"Address": 0x07A6E2, "DoorCount": 1, "Name": "Varia Suit Room"},
{"Address": 0x07A70B, "DoorCount": 1, "Name": "[Kraid Save Room]"},
{"Address": 0x07A734, "DoorCount": 1, "Name": "[Caterpillar Save Room]"},
{"Address": 0x07A75D, "DoorCount": 2, "Name": "Ice Beam Acid Room"},
{"Address": 0x07A788, "DoorCount": 2, "Name": "Cathedral"},
{"Address": 0x07A7B3, "DoorCount": 2, "Name": "Cathedral Entrance"},
{"Address": 0x07A7DE, "DoorCount": 8, "Name": "Business Center"},
{"Address": 0x07A815, "DoorCount": 4, "Name": "Ice Beam Gate Room"},
{"Address": 0x07A865, "DoorCount": 2, "Name": "Ice Beam Tutorial Room"},
{"Address": 0x07A890, "DoorCount": 1, "Name": "Ice Beam Room"},
{"Address": 0x07A8B9, "DoorCount": 3, "Name": "Ice Beam Snake Room"},
{"Address": 0x07A8F8, "DoorCount": 2, "Name": "Crumble Shaft"},
{"Address": 0x07A923, "DoorCount": 5, "Name": "Crocomire Speedway"},
{"Address": 0x07A98D, "DoorCount": 2, "Name": "Crocomire's Room"},
{"Address": 0x07A9E5, "DoorCount": 1, "Name": "Hi Jump Boots Room"},
{"Address": 0x07AA0E, "DoorCount": 2, "Name": "Crocomire Escape"},
{"Address": 0x07AA41, "DoorCount": 2, "Name": "Hi Jump Energy Tank Room"},
{"Address": 0x07AA82, "DoorCount": 4, "Name": "Post Crocomire Farming Room"},
{"Address": 0x07AAB5, "DoorCount": 1, "Name": "[Post Crocomire Save Room]"},
{"Address": 0x07AADE, "DoorCount": 1, "Name": "Post Crocomire Power Bomb Room"},
{"Address": 0x07AB07, "DoorCount": 4, "Name": "Post Crocomire Shaft"},
{"Address": 0x07AB3B, "DoorCount": 1, "Name": "Post Crocomire Missile Room"},
{"Address": 0x07AB64, "DoorCount": 2, "Name": "Grapple Tutorial Room 3"},
{"Address": 0x07AB8F, "DoorCount": 2, "Name": "Post Crocomire Jump Room"},
{"Address": 0x07ABD2, "DoorCount": 2, "Name": "Grapple Tutorial Room 2"},
{"Address": 0x07AC00, "DoorCount": 2, "Name": "Grapple Tutorial Room 1"},
{"Address": 0x07AC2B, "DoorCount": 2, "Name": "Grapple Beam Room"},
{"Address": 0x07AC5A, "DoorCount": 1, "Name": "Norfair Reserve Tank Room"},
{"Address": 0x07AC83, "DoorCount": 2, "Name": "Green Bubbles Missile Room"},
{"Address": 0x07ACB3, "DoorCount": 7, "Name": "Bubble Mountain"},
{"Address": 0x07ACF0, "DoorCount": 2, "Name": "Speed Booster Hall"},
{"Address": 0x07AD1B, "DoorCount": 1, "Name": "Speed Booster Room"},
{"Address": 0x07AD5E, "DoorCount": 5, "Name": "Single Chamber"},
{"Address": 0x07ADAD, "DoorCount": 3, "Name": "Double Chamber"},
{"Address": 0x07ADDE, "DoorCount": 1, "Name": "Wave Beam Room"},
{"Address": 0x07AE07, "DoorCount": 2, "Name": "Spiky Platforms Tunnel"},
{"Address": 0x07AE32, "DoorCount": 2, "Name": "Volcano Room"},
{"Address": 0x07AE74, "DoorCount": 4, "Name": "Kronic Boost Room"},
{"Address": 0x07AEB4, "DoorCount": 2, "Name": "Magdollite Tunnel"},
{"Address": 0x07AEDF, "DoorCount": 3, "Name": "Purple Shaft"},
{"Address": 0x07AF14, "DoorCount": 2, "Name": "Lava Dive Room"},
{"Address": 0x07AF3F, "DoorCount": 4, "Name": "[Elevator to Lower Norfair]"},
{"Address": 0x07AF72, "DoorCount": 3, "Name": "Upper Norfair Farming Room"},
{"Address": 0x07AFA3, "DoorCount": 2, "Name": "Rising Tide"},
{"Address": 0x07AFCE, "DoorCount": 3, "Name": "Acid Snakes Tunnel"},
{"Address": 0x07AFFB, "DoorCount": 2, "Name": "Spiky Acid Snakes Tunnel"},
{"Address": 0x07B026, "DoorCount": 2, "Name": "[Crocomire Recharge Room]"},
{"Address": 0x07B051, "DoorCount": 1, "Name": "Purple Farming Room"},
{"Address": 0x07B07A, "DoorCount": 2, "Name": "Bat Cave"},
{"Address": 0x07B0B4, "DoorCount": 1, "Name": "Norfair Map Room"},
{"Address": 0x07B0DD, "DoorCount": 1, "Name": "[Bubble Mountain Save Room]"},
{"Address": 0x07B106, "DoorCount": 2, "Name": "Frog Speedway"},
{"Address": 0x07B139, "DoorCount": 2, "Name": "Red Pirate Shaft"},
{"Address": 0x07B167, "DoorCount": 2, "Name": "[Business Center Save Room]"},
{"Address": 0x07B192, "DoorCount": 1, "Name": "[Crocomire Save Room]"},
{"Address": 0x07B1BB, "DoorCount": 1, "Name": "[Elevator Save Room]"},
{"Address": 0x07B1E5, "DoorCount": 2, "Name": "Acid Statue Room"},
{"Address": 0x07B236, "DoorCount": 4, "Name": "Main Hall"},
{"Address": 0x07B283, "DoorCount": 2, "Name": "Golden Torizo's Room"},
{"Address": 0x07B2DA, "DoorCount": 2, "Name": "Fast Ripper Room"},
{"Address": 0x07B305, "DoorCount": 1, "Name": "[Screw Attack Energy Charge Room]"},
{"Address": 0x07B32E, "DoorCount": 2, "Name": "Ridley's Room"},
{"Address": 0x07B37A, "DoorCount": 2, "Name": "Lower Norfair Farming Room"},
{"Address": 0x07B3A5, "DoorCount": 5, "Name": "Fast Pillars Setup Room"},
#{"Address": 0x07B3E1, "DoorCount": 1, "Name": "[[unused room]]"},
{"Address": 0x07B40A, "DoorCount": 2, "Name": "Mickey Mouse Room"},
{"Address": 0x07B457, "DoorCount": 2, "Name": "Pillar Room"},
{"Address": 0x07B482, "DoorCount": 2, "Name": "Plowerhouse Room"},
{"Address": 0x07B4AD, "DoorCount": 3, "Name": "The Worst Room In The Game"},
{"Address": 0x07B4E5, "DoorCount": 2, "Name": "Amphitheatre"},
{"Address": 0x07B510, "DoorCount": 3, "Name": "Lower Norfair Spring Ball Maze Room"},
{"Address": 0x07B55A, "DoorCount": 2, "Name": "Lower Norfair Escape Power Bomb Room"},
{"Address": 0x07B585, "DoorCount": 4, "Name": "Red Keyhunter Shaft"},
{"Address": 0x07B5D5, "DoorCount": 2, "Name": "Wasteland"},
{"Address": 0x07B62B, "DoorCount": 2, "Name": "Metal Pirates Room"},
{"Address": 0x07B656, "DoorCount": 2, "Name": "Three Muskateers' Room"},
{"Address": 0x07B698, "DoorCount": 1, "Name": "Ridley Tank Room"},
{"Address": 0x07B6C1, "DoorCount": 3, "Name": "Screw Attack Room"},
{"Address": 0x07B6EE, "DoorCount": 3, "Name": "Lower Norfair Fireflea Room"},
{"Address": 0x07B741, "DoorCount": 1, "Name": "[Red Keyhunter Shaft Save Room]"},
{"Address": 0x07C98E, "DoorCount": 3, "Name": "Bowling Alley"},
{"Address": 0x07CA08, "DoorCount": 2, "Name": "Wrecked Ship Entrance"},
{"Address": 0x07CA52, "DoorCount": 3, "Name": "Attic"},
{"Address": 0x07CAAE, "DoorCount": 1, "Name": "Wrecked Ship East Missile Room"},
{"Address": 0x07CAF6, "DoorCount": 7, "Name": "Wrecked Ship Main Shaft"},
{"Address": 0x07CB8B, "DoorCount": 2, "Name": "Spiky Death Room"},
{"Address": 0x07CBD5, "DoorCount": 3, "Name": "Electric Death Room"},
{"Address": 0x07CC27, "DoorCount": 1, "Name": "Wrecked Ship Energy Tank Room"},
{"Address": 0x07CC6F, "DoorCount": 3, "Name": "Basement"},
{"Address": 0x07CCCB, "DoorCount": 1, "Name": "Wrecked Ship Map Room"},
{"Address": 0x07CD13, "DoorCount": 1, "Name": "Phantoon's Room"},
{"Address": 0x07CD5C, "DoorCount": 2, "Name": "Sponge Bath"},
{"Address": 0x07CDA8, "DoorCount": 1, "Name": "Wrecked Ship West Super Room"},
{"Address": 0x07CDF1, "DoorCount": 1, "Name": "Wrecked Ship East Super Room"},
{"Address": 0x07CE40, "DoorCount": 2, "Name": "Gravity Suit Room"},
{"Address": 0x07CE8A, "DoorCount": 1, "Name": "[Wrecked Ship Save Room]"},
{"Address": 0x07CED2, "DoorCount": 1, "Name": "[Glass Tunnel Save Room]"},
{"Address": 0x07CEFB, "DoorCount": 4, "Name": "Glass Tunnel"},
{"Address": 0x07CF54, "DoorCount": 2, "Name": "West Tunnel"},
{"Address": 0x07CF80, "DoorCount": 3, "Name": "East Tunnel"},
{"Address": 0x07CFC9, "DoorCount": 5, "Name": "Main Street"},
{"Address": 0x07D017, "DoorCount": 4, "Name": "Fish Tank"},
{"Address": 0x07D055, "DoorCount": 1, "Name": "Mama Turtle Room"},
{"Address": 0x07D08A, "DoorCount": 2, "Name": "Crab Tunnel"},
{"Address": 0x07D0B9, "DoorCount": 6, "Name": "Mt. Everest"},
{"Address": 0x07D104, "DoorCount": 2, "Name": "Red Fish Room"},
{"Address": 0x07D13B, "DoorCount": 1, "Name": "Watering Hole"},
{"Address": 0x07D16D, "DoorCount": 2, "Name": "Northwest Maridia Bug Room"},
{"Address": 0x07D1A3, "DoorCount": 3, "Name": "Crab Shaft"},
{"Address": 0x07D1DD, "DoorCount": 3, "Name": "Pseudo Plasma Spark Room"},
{"Address": 0x07D21C, "DoorCount": 4, "Name": "Crab Hole"},
{"Address": 0x07D252, "DoorCount": 2, "Name": "[Tunnel to West Sand Hall]"},
{"Address": 0x07D27E, "DoorCount": 2, "Name": "Plasma Tutorial Room"},
{"Address": 0x07D2AA, "DoorCount": 1, "Name": "Plasma Room"},
{"Address": 0x07D2D9, "DoorCount": 2, "Name": "Thread The Needle Room"},
{"Address": 0x07D30B, "DoorCount": 4, "Name": "Maridia Elevator Room"},
{"Address": 0x07D340, "DoorCount": 4, "Name": "Plasma Spark Room"},
{"Address": 0x07D387, "DoorCount": 2, "Name": "Plasma Climb"},
{"Address": 0x07D3B6, "DoorCount": 1, "Name": "Maridia Map Room"},
{"Address": 0x07D3DF, "DoorCount": 1, "Name": "[Maridia Elevator Save Room]"},
{"Address": 0x07D408, "DoorCount": 2, "Name": "[Vertical Tube]"},
{"Address": 0x07D433, "DoorCount": 3, "Name": "Bug Sand Hole"},
{"Address": 0x07D461, "DoorCount": 3, "Name": "West Sand Hall"},
{"Address": 0x07D48E, "DoorCount": 3, "Name": "Oasis"},
{"Address": 0x07D4C2, "DoorCount": 3, "Name": "East Sand Hall"},
{"Address": 0x07D4EF, "DoorCount": 2, "Name": "West Sand Hole"},
{"Address": 0x07D51E, "DoorCount": 2, "Name": "East Sand Hole"},
{"Address": 0x07D54D, "DoorCount": 2, "Name": "[West Sand Fall]"},
{"Address": 0x07D57A, "DoorCount": 2, "Name": "[East Sand Fall]"},
{"Address": 0x07D5A7, "DoorCount": 6, "Name": "Aqueduct"},
{"Address": 0x07D5EC, "DoorCount": 2, "Name": "Butterfly Room"},
{"Address": 0x07D617, "DoorCount": 2, "Name": "Botwoon Hallway"},
{"Address": 0x07D646, "DoorCount": 4, "Name": "Pants Room"},
{"Address": 0x07D69A, "DoorCount": 2, "Name": "[Pants Room West half]"},
{"Address": 0x07D6D0, "DoorCount": 1, "Name": "Spring Ball Room"},
{"Address": 0x07D6FD, "DoorCount": 1, "Name": "Below Botwoon Energy Tank"},
{"Address": 0x07D72A, "DoorCount": 3, "Name": "Colosseum"},
{"Address": 0x07D765, "DoorCount": 1, "Name": "[Aqueduct Save Room]"},
{"Address": 0x07D78F, "DoorCount": 2, "Name": "The Precious Room"},
{"Address": 0x07D7E4, "DoorCount": 4, "Name": "Botwoon Energy Tank Room"},
{"Address": 0x07D81A, "DoorCount": 2, "Name": "[Colosseum Save Room]"},
{"Address": 0x07D845, "DoorCount": 1, "Name": "[Halfie Climb Missile Station]"},
{"Address": 0x07D86E, "DoorCount": 1, "Name": "[Bug Sand Fall]"},
{"Address": 0x07D898, "DoorCount": 2, "Name": "[Botwoon Sand Fall]"},
{"Address": 0x07D8C5, "DoorCount": 2, "Name": "Shaktool Room"},
{"Address": 0x07D913, "DoorCount": 4, "Name": "Halfie Climb Room"},
{"Address": 0x07D95E, "DoorCount": 2, "Name": "Botwoon's Room"},
{"Address": 0x07D9AA, "DoorCount": 1, "Name": "Space Jump Room"},
{"Address": 0x07D9D4, "DoorCount": 1, "Name": "[Colosseum Energy Charge Room]"},
{"Address": 0x07D9FE, "DoorCount": 2, "Name": "Cactus Alley [West]"},
{"Address": 0x07DA2B, "DoorCount": 2, "Name": "Cactus Alley [East]"},
{"Address": 0x07DA60, "DoorCount": 2, "Name": "Draygon's Room"},
{"Address": 0x07DAAE, "DoorCount": 4, "Name": "Tourian First Room"},
{"Address": 0x07DAE1, "DoorCount": 2, "Name": "Metroid Room 1"},
{"Address": 0x07DB31, "DoorCount": 2, "Name": "Metroid Room 2"},
{"Address": 0x07DB7D, "DoorCount": 2, "Name": "Metroid Room 3"},
{"Address": 0x07DBCD, "DoorCount": 2, "Name": "Metroid Room 4"},
{"Address": 0x07DC19, "DoorCount": 2, "Name": "Blue Hopper Room"},
{"Address": 0x07DC65, "DoorCount": 2, "Name": "Dust Torizo Room"},
{"Address": 0x07DCB1, "DoorCount": 2, "Name": "Big Boy Room"},
{"Address": 0x07DCFF, "DoorCount": 3, "Name": "Seaweed Room"},
{"Address": 0x07DD2E, "DoorCount": 1, "Name": "Tourian Recharge Room"},
{"Address": 0x07DD58, "DoorCount": 2, "Name": "Mother Brain Room"},
{"Address": 0x07DDC4, "DoorCount": 2, "Name": "Tourian Eye Door Room"},
{"Address": 0x07DDF3, "DoorCount": 3, "Name": "Rinka Shaft"},
{"Address": 0x07DE23, "DoorCount": 1, "Name": "[Mother Brain Save Room]"},
{"Address": 0x07DE4D, "DoorCount": 2, "Name": "Tourian Escape Room 1"},
{"Address": 0x07DE7A, "DoorCount": 2, "Name": "Tourian Escape Room 2"},
{"Address": 0x07DEA7, "DoorCount": 2, "Name": "Tourian Escape Room 3"},
{"Address": 0x07DEDE, "DoorCount": 2, "Name": "Tourian Escape Room 4"},
{"Address": 0x07DF1B, "DoorCount": 1, "Name": "[Tourian First Save Room]"},
{"Address": 0x07DF45, "DoorCount": 1, "Name": "[Ceres Elevator Room]"},
{"Address": 0x07DF8D, "DoorCount": 2, "Name": "[Ceres Jump Tutorial Room]"},
{"Address": 0x07DFD7, "DoorCount": 2, "Name": "[Ceres Staircase Room]"},
{"Address": 0x07E021, "DoorCount": 2, "Name": "[Ceres Dead Scientists Room]"},
{"Address": 0x07E06B, "DoorCount": 2, "Name": "[Ceres Last Corridor]"},
{"Address": 0x07E0B5, "DoorCount": 1, "Name": "[Ceres Ridley Room]"},
#{"Address": 0x07E82C, "DoorCount": 4, "Name": "[Tile Debug Room]"}
]
