;;; compile with asar v1.81 (https://github.com/RPGHacker/asar/releases/tag/v1.81)

arch 65816
lorom

;;; update scroll set by door ptr
incsrc "macros.asm"

;;; Red (00): prevents the camera from being able to see certain screens, either permanently, or until a scroll PLM or a door's ASM pointer changes it to blue or green.
;;; Blue (01): Samus can explore these freely. Blue scrolls display all but the very top and bottom two rows of the current screen, which is ideal for hallways.
;;; Green (02): same as blue, except green scrolls allow the bottom two rows of the current screen to be seen. Not preferred because this causes the camera to hang lower towards the foreground instead of showing the player more of what's going on around Samus. However, doors that are in the floor must be inside of a green scroll to work.

;;; generated by tools/gen_door_asm.py
;;; Door to Room $92fd: Parlor and Alcatraz
org $8fb981
    PHP
    SEP #$20
    LDA #$02
    STA $7ecd28
    PLP
    RTS

;;; Door to Room $92fd: Parlor and Alcatraz
org $8fb98c
    PHP
    SEP #$20
    LDA #$01
    STA $7ecd24
    PLP
    RTS

;;; Door to Room $91f8: Landing Site
org $8fb997
    PHP
    SEP #$20
    LDA #$01
    STA $7ecd39
    PLP
    RTS

;;; Door to Room $92fd: Parlor and Alcatraz
org $8fb9a2
    PHP
    SEP #$20
    LDA #$00
    STA $7ecd20
    LDA #$02
    STA $7ecd26
    PLP
    RTS

;;; Door to Room $c98e: Bowling Alley
org $8fb9b3
    PHP
    SEP #$20
    LDA #$00
    STA $7ecd29
    STA $7ecd28
    STA $7ecd27
    STA $7ecd26
    PLP
    RTS

;;; Door to Room $c98e: Bowling Alley
org $8fb9ca
    PHP
    SEP #$20
    LDA #$00
    STA $7ecd23
    STA $7ecd22
    STA $7ecd21
    STA $7ecd20
    STA $7ecd26
    STA $7ecd31
    STA $7ecd30
    STA $7ecd2c
    PLP
    RTS

;;; Door to Room $948c: Crateria Keyhunter Room
org $8fb9f1
    PHP
    SEP #$20
    LDA #$02
    STA $7ecd21
    STA $7ecd24
    PLP
    RTS

;;; Door to Room $96ba: Climb
org $8fba00
    PHP
    SEP #$20
    LDA #$01
    STA $7ecd20
    PLP
    RTS

;;; Door to Room $96ba: Climb
org $8fba0b
    PHP
    SEP #$20
    LDA #$01
    STA $7ecd35
    PLP
    RTS

;;; Door to Room $965b: Gauntlet Energy Tank Room
org $8fba16
    PHP
    SEP #$20
    LDA #$01
    STA $7ecd21
    PLP
    RTS

;;; Door to Room $a322: Caterpillar Room
org $8fba21
    PHP
    SEP #$20
    LDA #$02
    STA $7ecd28
    PLP
    RTS

;;; Door to Room $99bd: Green Pirates Shaft
org $8fba2c
    PHP
    SEP #$20
    LDA #$02
    STA $7ecd23
    PLP
    RTS

;;; Door to Room $9ad9: Green Brinstar Main Shaft [etecoon room]
org $8fbd07
    PHP
    SEP #$20
    LDA #$02
    STA $7ecd3b
    STA $7ecd3f
    PLP
    RTS

;;; Door to Room $a011: Etecoon Energy Tank Room
org $8fbd16
    PHP
    SEP #$20
    LDA #$01
    STA $7ecd29
    STA $7ecd28
    PLP
    RTS

;;; Door to Room $9ad9: Green Brinstar Main Shaft [etecoon room]
org $8fbd25
    PHP
    SEP #$20
    LDA #$01
    STA $7ecd3e
    PLP
    RTS

;;; Door to Room $9e11: Pink Brinstar Power Bomb Room
org $8fbd30
    PHP
    SEP #$20
    LDA #$02
    STA $7ecd23
    STA $7ecd22
    PLP
    RTS

;;; Door to Room $a6a1: Warehouse Entrance
org $8fbd3f
    PHP
    SEP #$20
    LDA #$00
    STA $7ecd22
    LDA #$02
    STA $7ecd21
    PLP
    RTS

;;; Door to Room $9cb3: Dachora Room
org $8fbd50
    PHP
    SEP #$20
    LDA #$02
    STA $7ecd29
    PLP
    RTS

;;; Door to Room $9d19: Big Pink
org $8fbd5b
    PHP
    SEP #$20
    LDA #$00
    STA $7ecd3a
    LDA #$01
    STA $7ecd39
    PLP
    RTS

;;; Door to Room $9cb3: Dachora Room
org $8fbd6c
    PHP
    SEP #$20
    LDA #$00
    STA $7ecd22
    PLP
    RTS

;;; Door to Room $9d19: Big Pink
org $8fbd77
    PHP
    SEP #$20
    LDA #$02
    STA $7ecd40
    STA $7ecd46
    STA $7ecd45
    PLP
    RTS

;;; Door to Room $9f64: Blue Brinstar Energy Tank Room
org $8fbd8a
    PHP
    SEP #$20
    LDA #$01
    STA $7ecd20
    PLP
    RTS

;;; Door to Room $a56b: Kraid Eye Door Room
org $8fbd95
    PHP
    SEP #$20
    LDA #$02
    STA $7ecd21
    PLP
    RTS

;;; Door to Room $a253: Red Tower
org $8fbda0
    PHP
    SEP #$20
    LDA #$02
    STA $7ecd26
    STA $7ecd27
    PLP
    RTS

;;; Door to Room $d104: Red Fish Room
org $8fbdaf
    PHP
    SEP #$20
    LDA #$01
    STA $7ecd21
    LDA #$00
    STA $7ecd20
    PLP
    RTS

;;; Door to Room $9b5b: Spore Spawn Super Room
org $8fbdc0
    PHP
    SEP #$20
    LDA #$01
    STA $7ecd20
    LDA #$00
    STA $7ecd22
    PLP
    RTS

;;; Door to Room $cf80: East Tunnel
org $8fbdd1
    PHP
    SEP #$20
    LDA #$00
    STA $7ecd23
    LDA #$01
    STA $7ecd27
    PLP
    RTS

;;; Door to Room $a4da: Warehouse Keyhunter Room
org $8fbde2
    PHP
    SEP #$20
    LDA #$01
    STA $7ecd21
    STA $7ecd20
    PLP
    RTS

;;; Door to Room $a408: Below Spazer
org $8fbdf1
    PHP
    SEP #$20
    LDA #$02
    STA $7ecd21
    STA $7ecd20
    PLP
    RTS

;;; Door to Room $9d19: Big Pink
org $8fbe00
    PHP
    SEP #$20
    LDA #$02
    STA $7ecd23
    PLP
    RTS

;;; Door to Room $a322: Caterpillar Room
org $8fbe0b
    PHP
    SEP #$20
    LDA #$02
    STA $7ecd31
    STA $7ecd34
    PLP
    RTS

;;; Door to Room $a322: Caterpillar Room
org $8fbe1a
    PHP
    SEP #$20
    LDA #$02
    STA $7ecd28
    PLP
    RTS

;;; Door to Room $9f11: Construction Zone
org $8fbe25
    PHP
    SEP #$20
    LDA #$02
    STA $7ecd20
    LDA #$01
    STA $7ecd21
    PLP
    RTS

;;; Door to Room $9938: [Elevator to Green Brinstar]
org $8fbe36
    SEP #$20
    LDA #$02
    STA $7ecd22
    RTS

;;; Door to Room $b1e5: Acid Statue Room
org $8fbf9e
    PHP
    SEP #$20
    LDA #$00
    STA $7ecd25
    STA $7ecd24
    LDA #$01
    STA $7ecd28
    STA $7ecd27
    STA $7ecd26
    PLP
    RTS

;;; Door to Room $b510: Lower Norfair Spring Ball Maze Room
org $8fbfbb
    PHP
    SEP #$20
    LDA #$01
    STA $7ecd23
    STA $7ecd22
    STA $7ecd21
    LDA #$02
    STA $7ecd20
    LDA #$00
    STA $7ecd28
    PLP
    RTS

;;; Door to Room $a98d: Crocomire's Room
org $8fbfda
    PHP
    SEP #$20
    LDA #$01
    STA $7ecd27
    STA $7ecd26
    PLP
    RTS

;;; Door to Room $b07a: Bat Cave
org $8fbfe9
    PHP
    SEP #$20
    LDA #$00
    STA $7ecd21
    LDA #$01
    STA $7ecd20
    PLP
    RTS

;;; Door to Room $a815: Ice Beam Gate Room
org $8fbffa
    PHP
    SEP #$20
    LDA #$02
    STA $7ecd2a
    PLP
    RTS

;;; Door to Room $aa41: Hi Jump Energy Tank Room
org $8fc016
    PHP
    SEP #$20
    LDA #$02
    STA $7ecd21
    STA $7ecd23
    PLP
    RTS

;;; Door to Room $ae32: Volcano Room
org $8fc025
    PHP
    SEP #$20
    LDA #$01
    STA $7ecd28
    STA $7ecd27
    LDA #$00
    STA $7ecd26
    PLP
    RTS

;;; Door to Room $a8b9: Ice Beam Snake Room
org $8fc03a
    PHP
    SEP #$20
    LDA #$00
    STA $7ecd23
    LDA #$01
    STA $7ecd22
    PLP
    RTS

;;; Door to Room $b5d5: Wasteland
org $8fc04b
    PHP
    SEP #$20
    LDA #$02
    STA $7ecd2a
    PLP
    RTS

;;; Door to Room $b3a5: Fast Pillars Setup Room
org $8fc056
    PHP
    SEP #$20
    LDA #$00
    STA $7ecd21
    LDA #$01
    STA $7ecd22
    PLP
    RTS

;;; Door to Room $b585: Red Keyhunter Shaft
org $8fc067
    PHP
    SEP #$20
    LDA #$00
    STA $7ecd25
    LDA #$01
    STA $7ecd22
    PLP
    RTS

;;; Door to Room $b6ee: Lower Norfair Fireflea Room
org $8fc078
    PHP
    SEP #$20
    LDA #$01
    STA $7ecd21
    LDA #$00
    STA $7ecd24
    PLP
    RTS

;;; Door to Room $b283: Golden Torizo's Room
org $8fc089
    PHP
    SEP #$20
    LDA #$01
    STA $7ecd21
    LDA #$00
    STA $7ecd20
    STA $7ecd23
    STA $7ecd22
    PLP
    RTS

;;; Door to Room $b4ad: The Worst Room In The Game
org $8fc0a2
    PHP
    SEP #$20
    LDA #$02
    STA $7ecd20
    PLP
    RTS

;;; Door to Room $b6ee: Lower Norfair Fireflea Room
org $8fc0ad
    PHP
    SEP #$20
    LDA #$01
    STA $7ecd22
    STA $7ecd21
    LDA #$00
    STA $7ecd24
    PLP
    RTS

;;; Door to Room $b585: Red Keyhunter Shaft
org $8fc0c2
    PHP
    SEP #$20
    LDA #$01
    STA $7ecd22
    LDA #$00
    STA $7ecd25
    PLP
    RTS

;;; Door to Room $ac83: Green Bubbles Missile Room
org $8fc0d3
    PHP
    SEP #$20
    LDA #$01
    STA $7ecd21
    PLP
    RTS

;;; Door to Room $aedf: Purple Shaft
org $8fc0de
    PHP
    SEP #$20
    LDA #$01
    STA $7ecd20
    LDA #$00
    STA $7ecd21
    PLP
    RTS

;;; Door to Room $a815: Ice Beam Gate Room
org $8fc0ef
    PHP
    SEP #$20
    LDA #$01
    STA $7ecd38
    PLP
    RTS

;;; Door to Room $ae74: Kronic Boost Room
org $8fc0fa
    PHP
    SEP #$20
    LDA #$00
    STA $7ecd22
    LDA #$01
    STA $7ecd23
    PLP
    RTS

;;; Door to Room $b40a: Mickey Mouse Room
org $8fc10b
    PHP
    SEP #$20
    LDA #$00
    STA $7ecd2d
    PLP
    RTS

;;; Door to Room $cd5c: Sponge Bath
org $8fe1e8
    PHP
    SEP #$20
    LDA #$01
    STA $7ecd20
    PLP
    RTS

;;; Door to Room $cbd5: Electric Death Room
org $8fe1f3
    PHP
    SEP #$20
    LDA #$02
    STA $7ecd20
    PLP
    RTS

;;; Door to Room $cc6f: Basement
org $8fe1fe
    PHP
    SEP #$20
    LDA #$00
    STA $7ecd21
    LDA #$01
    STA $7ecd20
    PLP
    RTS

;;; Door to Room $caf6: Wrecked Ship Main Shaft
org $8fe20f
    PHP
    SEP #$20
    LDA #$01
    STA $7ecd44
    PLP
    RTS

;;; Door to Room $caf6: Wrecked Ship Main Shaft
org $8fe21a
    PHP
    SEP #$20
    LDA #$02
    STA $7ecd45
    STA $7ecd4b
    PLP
    RTS

;;; Door to Room $c98e: Bowling Alley
org $8fe229
    PHP
    SEP #$20
    LDA #$00
    STA $7ecd2b
    STA $7ecd2a
    STA $7ecd29
    STA $7ecd28
    STA $7ecd27
    STA $7ecd26
    PLP
    RTS

;;; Door to Room $d913: Halfie Climb Room
org $8fe318
    PHP
    SEP #$20
    LDA #$00
    STA $7ecd2e
    LDA #$01
    STA $7ecd2d
    PLP
    RTS

;;; Door to Room $cf80: East Tunnel
org $8fe345
    PHP
    SEP #$20
    LDA #$00
    STA $7ecd23
    LDA #$01
    STA $7ecd27
    PLP
    RTS

;;; Door to Room $d21c: Crab Hole
org $8fe356
    PHP
    SEP #$20
    LDA #$00
    STA $7ecd20
    LDA #$01
    STA $7ecd21
    PLP
    RTS

;;; Door to Room $a322: Caterpillar Room
org $8fe367
    PHP
    SEP #$20
    LDA #$00
    STA $7ecd2b
    LDA #$01
    STA $7ecd2a
    PLP
    RTS

;;; Door to Room $cefb: Glass Tunnel
org $8fe378
    PHP
    SEP #$20
    LDA #$00
    STA $7ecd20
    STA $7ecd22
    LDA #$01
    STA $7ecd21
    PLP
    RTS

;;; Door to Room $d95e: Botwoon's Room
org $8fe38d
    PHP
    SEP #$20
    LDA #$01
    STA $7ecd20
    PLP
    RTS

;;; Door to Room $d1a3: Crab Shaft
org $8fe398
    PHP
    SEP #$20
    LDA #$01
    STA $7ecd27
    PLP
    RTS

;;; Door to Room $d646: Pants Room
org $8fe3a3
    PHP
    SEP #$20
    LDA #$00
    STA $7ecd25
    PLP
    RTS

;;; Door to Room $d646: Pants Room
org $8fe3b9
    PHP
    SEP #$20
    LDA #$00
    STA $7ecd25
    STA $7ecd26
    PLP
    RTS

;;; Door to Room $d69a: [Pants Room West half]
org $8fe3c8
    PHP
    SEP #$20
    LDA #$00
    STA $7ecd22
    LDA #$01
    STA $7ecd21
    PLP
    RTS

;;; Door to Room $d78f: The Precious Room
org $8fe3d9
    PHP
    SEP #$20
    LDA #$02
    STA $7ecd21
    STA $7ecd23
    PLP
    RTS

;;; Door to Room $a66a: Statues Room
org $8fe4c0
    PHP
    SEP #$20
    LDA #$02
    STA $7ecd20
    STA $7ecd21
    PLP
    RTS

;;; Door to Room $96ba: Climb
org $8fe4cf
    PHP
    SEP #$20
    LDA #$01
    STA $7ecd3a
    LDA #$00
    STA $7ecd39
    PLP
    RTS


;;; for incompatible transition leading to WS basement phantoon out door
;;; add in freespace
org $8FFE71
%export(PhantoonRoomOut_DoorAsmPtr)
        PHP
        SEP #$20
        LDA #$01
        STA $7ECD20
        PLP
        RTS

warnpc $8ffe7c
